using System.Text.Json;
using System.Text.Json.Serialization;

namespace Icoder.Sdk;

public sealed record GuidedLabel
{
    [JsonPropertyName("key")]
    public required string Key { get; init; }

    [JsonPropertyName("value")]
    public required string Value { get; init; }
}

public sealed record GuidedTemplateVersion
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("versionNumber")]
    public int VersionNumber { get; init; }

    [JsonPropertyName("generation")]
    public JsonElement Generation { get; init; }

    [JsonPropertyName("deletedAt")]
    public string? DeletedAt { get; init; }
}

public sealed record GuidedTemplate
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("inheritedFromId")]
    public string? InheritedFromId { get; init; }

    [JsonPropertyName("autoGenerated")]
    public bool? AutoGenerated { get; init; }

    [JsonPropertyName("source")]
    public string? Source { get; init; }

    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("description")]
    public string Description { get; init; } = "";

    [JsonPropertyName("languages")]
    public IReadOnlyList<string> Languages { get; init; } = [];

    [JsonPropertyName("regions")]
    public IReadOnlyList<string> Regions { get; init; } = [];

    [JsonPropertyName("specialties")]
    public IReadOnlyList<string> Specialties { get; init; } = [];

    [JsonPropertyName("labels")]
    public IReadOnlyList<GuidedLabel> Labels { get; init; } = [];

    [JsonPropertyName("publishedVersion")]
    public GuidedTemplateVersion? PublishedVersion { get; init; }

    [JsonPropertyName("createdBy")]
    public string? CreatedBy { get; init; }

    [JsonPropertyName("createdAt")]
    public string CreatedAt { get; init; } = "";

    [JsonPropertyName("updatedAt")]
    public string UpdatedAt { get; init; } = "";

    [JsonPropertyName("deletedAt")]
    public string? DeletedAt { get; init; }
}

public sealed record GuidedSection
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("inheritedFromId")]
    public string? InheritedFromId { get; init; }

    [JsonPropertyName("autoGenerated")]
    public bool? AutoGenerated { get; init; }

    [JsonPropertyName("source")]
    public string? Source { get; init; }

    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("languages")]
    public IReadOnlyList<string> Languages { get; init; } = [];

    [JsonPropertyName("regions")]
    public IReadOnlyList<string> Regions { get; init; } = [];

    [JsonPropertyName("specialties")]
    public IReadOnlyList<string> Specialties { get; init; } = [];

    [JsonPropertyName("labels")]
    public IReadOnlyList<GuidedLabel> Labels { get; init; } = [];

    [JsonPropertyName("createdBy")]
    public string? CreatedBy { get; init; }

    [JsonPropertyName("createdAt")]
    public string CreatedAt { get; init; } = "";

    [JsonPropertyName("updatedAt")]
    public string UpdatedAt { get; init; } = "";

    [JsonPropertyName("deletedAt")]
    public string? DeletedAt { get; init; }

    [JsonPropertyName("versionId")]
    public string? VersionId { get; init; }

    [JsonPropertyName("generation")]
    public JsonElement? Generation { get; init; }
}

public sealed record GuidedDiscoveryFilters
{
    public IReadOnlyList<string> Languages { get; init; } = [];
    public IReadOnlyList<string> Regions { get; init; } = [];
    public IReadOnlyList<string> Specialties { get; init; } = [];
    public IReadOnlyList<string> Labels { get; init; } = [];
    public bool? Published { get; init; }
    public string? Source { get; init; }
}

public sealed record SectionCreateRequest
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("language")]
    public string? Language { get; init; }

    [JsonPropertyName("specialties")]
    public IReadOnlyList<string>? Specialties { get; init; }

    [JsonPropertyName("labels")]
    public IReadOnlyList<GuidedLabel>? Labels { get; init; }

    [JsonPropertyName("outputSchema")]
    public IReadOnlyDictionary<string, object?>? OutputSchema { get; init; }
}

public sealed record SectionUpdateRequest
{
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("language")]
    public string? Language { get; init; }

    [JsonPropertyName("specialties")]
    public IReadOnlyList<string>? Specialties { get; init; }

    [JsonPropertyName("labels")]
    public IReadOnlyList<GuidedLabel>? Labels { get; init; }

    [JsonPropertyName("outputSchema")]
    public IReadOnlyDictionary<string, object?>? OutputSchema { get; init; }
}

public sealed class TemplatesResource(ICoDerClient client)
{
    public Task<IReadOnlyList<GuidedTemplate>> ListAsync(
        GuidedDiscoveryFilters? filters = null,
        CancellationToken cancellationToken = default,
        ICoDerRequestOptions? requestOptions = null)
        => client.SendAsync<IReadOnlyList<GuidedTemplate>>(
            HttpMethod.Get,
            "/api/v2/tools/templates/" + BuildQuery(filters),
            cancellationToken: cancellationToken, requestOptions: requestOptions);

    public Task<GuidedTemplate> GetAsync(
        string templateId,
        CancellationToken cancellationToken = default,
        ICoDerRequestOptions? requestOptions = null)
    {
        ValidateId(templateId, nameof(templateId));
        return client.SendAsync<GuidedTemplate>(
            HttpMethod.Get,
            $"/api/v2/tools/templates/{Escape(templateId)}",
            cancellationToken: cancellationToken, requestOptions: requestOptions);
    }

    public Task<GuidedTemplateVersion> PublishAsync(
        string templateId,
        CancellationToken cancellationToken = default,
        ICoDerRequestOptions? requestOptions = null)
    {
        ValidateId(templateId, nameof(templateId));
        return client.SendAsync<GuidedTemplateVersion>(
            HttpMethod.Post,
            $"/api/v2/tools/templates/{Escape(templateId)}/publish",
            cancellationToken: cancellationToken, requestOptions: requestOptions);
    }

    public Task<IReadOnlyList<GuidedSection>> ListSectionsAsync(
        GuidedDiscoveryFilters? filters = null,
        CancellationToken cancellationToken = default,
        ICoDerRequestOptions? requestOptions = null)
        => client.SendAsync<IReadOnlyList<GuidedSection>>(
            HttpMethod.Get,
            "/api/v2/tools/sections/" + BuildQuery(filters),
            cancellationToken: cancellationToken, requestOptions: requestOptions);

    public Task<GuidedSection> GetSectionAsync(
        string sectionId,
        CancellationToken cancellationToken = default,
        ICoDerRequestOptions? requestOptions = null)
    {
        ValidateId(sectionId, nameof(sectionId));
        return client.SendAsync<GuidedSection>(
            HttpMethod.Get,
            $"/api/v2/tools/sections/{Escape(sectionId)}",
            cancellationToken: cancellationToken, requestOptions: requestOptions);
    }

    public Task<GuidedSection> CreateSectionAsync(
        SectionCreateRequest request,
        CancellationToken cancellationToken = default,
        ICoDerRequestOptions? requestOptions = null)
    {
        Guard.NotNull(request, nameof(request));
        Guard.NotNullOrWhiteSpace(request.Name, nameof(request.Name));
        return client.SendAsync<GuidedSection>(
            HttpMethod.Post,
            "/api/v2/tools/sections/",
            request,
            cancellationToken: cancellationToken, requestOptions: requestOptions);
    }

    public Task<GuidedSection> UpdateSectionAsync(
        string sectionId,
        SectionUpdateRequest request,
        CancellationToken cancellationToken = default,
        ICoDerRequestOptions? requestOptions = null)
    {
        ValidateId(sectionId, nameof(sectionId));
        Guard.NotNull(request, nameof(request));
        return client.SendAsync<GuidedSection>(
            Compatibility.Patch,
            $"/api/v2/tools/sections/{Escape(sectionId)}",
            request,
            cancellationToken: cancellationToken, requestOptions: requestOptions);
    }

    public Task DeleteSectionAsync(
        string sectionId,
        CancellationToken cancellationToken = default,
        ICoDerRequestOptions? requestOptions = null)
    {
        ValidateId(sectionId, nameof(sectionId));
        return client.SendNoContentAsync(
            HttpMethod.Delete,
            $"/api/v2/tools/sections/{Escape(sectionId)}",
            cancellationToken,
            requestOptions: requestOptions);
    }

    private static string BuildQuery(GuidedDiscoveryFilters? filters)
    {
        if (filters is null)
        {
            return "";
        }
        var parts = new List<string>();
        AddMany(parts, "lang", filters.Languages);
        AddMany(parts, "region", filters.Regions);
        AddMany(parts, "specialty", filters.Specialties);
        AddMany(parts, "label", filters.Labels);
        if (filters.Published is not null)
        {
            parts.Add($"published={filters.Published.Value.ToString().ToLowerInvariant()}");
        }
        if (!string.IsNullOrWhiteSpace(filters.Source))
        {
            if (filters.Source is not ("user" or "corti" or "project"))
            {
                throw new ArgumentException("Unsupported discovery source.", nameof(filters));
            }
            parts.Add($"source={Escape(filters.Source)}");
        }
        return parts.Count == 0 ? "" : "?" + string.Join("&", parts);
    }

    private static void AddMany(
        ICollection<string> parts,
        string key,
        IEnumerable<string> values)
    {
        foreach (var value in values)
        {
            if (!string.IsNullOrWhiteSpace(value))
            {
                parts.Add($"{key}={Escape(value)}");
            }
        }
    }

    private static string Escape(string value) => Uri.EscapeDataString(value);

    private static void ValidateId(string value, string parameterName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("Identifier cannot be empty.", parameterName);
        }
    }
}
