"""Tenant-scoped public identifiers for Guided Template compatibility."""

from __future__ import annotations

import uuid
import json
import hashlib
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.template import Template
from app.models.template import TemplateCategory, TemplateLanguage, TemplateScope


PUBLIC_TEMPLATE_NAMESPACE = uuid.UUID("9d53592f-2276-466b-a53a-ff6d955aafaf")
PUBLIC_TEMPLATE_VERSION_NAMESPACE = uuid.UUID("cfd0c8a8-3de6-4b08-a00d-e908bb4f1981")


def public_template_id(row: Template) -> str:
    return str(uuid.uuid5(
        PUBLIC_TEMPLATE_NAMESPACE,
        f"{row.organization_id}:{row.id}",
    ))


def public_template_version_id(row: Template) -> str:
    version_marker = hashlib.sha256((row.content or "").encode("utf-8")).hexdigest()
    return str(uuid.uuid5(
        PUBLIC_TEMPLATE_VERSION_NAMESPACE,
        f"{row.organization_id}:{row.id}:{version_marker}",
    ))


async def resolve_public_template(
    db: AsyncSession,
    *,
    organization_id: str,
    template_id: str,
) -> Template | None:
    """Resolve an opaque Guided ID without exposing legacy 12-char IDs."""
    rows = list((await db.scalars(
        select(Template).where(
            Template.organization_id == organization_id,
            Template.deleted_at.is_(None),
        )
    )).all())
    return next((row for row in rows if public_template_id(row) == template_id), None)


async def create_auto_template(
    db: AsyncSession,
    *,
    organization_id: str,
    name: str,
    output_language: str,
    definition: dict[str, Any],
) -> Template:
    """Persist an assembly/dynamic aggregate before document generation."""
    row = Template(
        organization_id=organization_id,
        name=name.strip(),
        description="Auto-generated Guided Document template aggregate.",
        content=json.dumps(definition, ensure_ascii=False, separators=(",", ":")),
        category=TemplateCategory.CUSTOM,
        language=(
            TemplateLanguage.ZH_CN
            if output_language.casefold().startswith("zh")
            else TemplateLanguage.EN_US
        ),
        scope=TemplateScope.ALL_CUSTOMERS,
        is_builtin=False,
    )
    db.add(row)
    await db.flush()
    return row


def template_definition(row: Template) -> dict[str, Any] | None:
    try:
        value = json.loads(row.content)
    except (TypeError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def template_generation(row: Template) -> dict[str, Any]:
    """Normalize a Builder draft into Corti's published generation shape."""
    definition = template_definition(row)
    if isinstance(definition, dict) and isinstance(definition.get("instructions"), dict):
        generation: dict[str, Any] = {
            "instructions": dict(definition["instructions"]),
        }
        if not isinstance(generation["instructions"].get("prompt"), str):
            generation["instructions"]["prompt"] = ""
        if isinstance(definition.get("sections"), list):
            resolved_sections = []
            language = getattr(row.language, "value", str(row.language))
            specialty = getattr(row.category, "value", str(row.category))
            created_at = row.created_at or row.updated_at
            updated_at = row.updated_at or created_at
            for raw in definition["sections"]:
                if not isinstance(raw, dict):
                    continue
                raw_id = raw.get("sectionId") or raw.get("id")
                if not raw_id:
                    continue
                try:
                    section_id = str(uuid.UUID(str(raw_id)))
                except ValueError:
                    section_id = str(uuid.uuid5(PUBLIC_TEMPLATE_NAMESPACE, str(raw_id)))
                instructions = raw.get("instructions", {})
                description = (
                    instructions.get("contentPrompt")
                    if isinstance(instructions, dict)
                    else None
                )
                labels = raw.get("labels", [])
                if not isinstance(labels, list):
                    labels = []
                resolved_sections.append({
                    "id": section_id,
                    "inheritedFromId": raw.get("inheritedFromId"),
                    "autoGenerated": False,
                    "source": "project",
                    "name": str(raw.get("heading") or raw.get("name") or raw_id),
                    "description": description,
                    "languages": [language],
                    "regions": ["CHN" if language == "zh-CN" else "USA"],
                    "specialties": raw.get("specialties") or [specialty],
                    "labels": [
                        item for item in labels
                        if isinstance(item, dict) and item.get("key") and item.get("value")
                    ],
                    "createdAt": created_at.isoformat() if created_at else "2026-08-14T00:00:00Z",
                    "updatedAt": updated_at.isoformat() if updated_at else "2026-08-14T00:00:00Z",
                    "deletedAt": None,
                })
            if resolved_sections:
                generation["sections"] = resolved_sections
        return generation
    return {"instructions": {"prompt": row.content or ""}}
