"""Orchestrator: state machine + planner + delegator + aggregator + inbound handler."""

from .aggregator import Aggregator, AggregatorConfig, AggregatorError
from .delegator import (
    Delegator,
    DelegatorConfig,
    ExpertInvocation,
    ExpertInvocationError,
    ExpertInvoker,
)
from .errors import OrchestratorError, OrchestratorStateError
from .events import OrchestratorEvent
from .inbound_handler import (
    DictAgentProvider,
    InboundHandler,
    InboundHandlerConfig,
    InboundMessage,
    InboundRequest,
    InboundResponse,
    extract_text_from_parts,
    is_valid_request,
    make_context_id,
    make_message_id,
    make_run_id,
)
from .metrics import (
    InMemoryBackend,
    MetricsBackend,
    OrchestratorMetrics,
    get_metrics,
    reset_default_metrics,
)
from .phi_redactor import (
    PHIRedactionError,
    PHIRedactionResult,
    PHIRedactor,
)
from .planner import (
    LLMCall,
    LLMResponse,
    Planner,
    PlannerConfig,
    PlannerError,
)
from .prompts import (
    NON_GOALS_NOTICE,
    ORCHESTRATOR_SYSTEM_PROMPT,
    PHI_REDACTION_NOTICE,
    PLAN_SCHEMA_DESCRIPTION,
    PRODUCTION_WRITEBACK_BLOCKED,
    assert_prompt_invariants,
    build_planner_user_message,
    build_planner_user_message_from_agent,
)
from .recorder_adapter import (
    NoopRecorder,
    NoopRun,
    NoopStage,
    RecorderAdapter,
    RecorderLike,
    STAGE_AGGREGATED,
    STAGE_AGGREGATING_STARTED,
    STAGE_DELEGATING_STARTED,
    STAGE_EXPERT_INVOKED,
    STAGE_EXPERT_RETURNED,
    STAGE_INBOUND_RECEIVED,
    STAGE_PHI_REDACTED,
    STAGE_PLAN_GENERATED,
    STAGE_PLANNING_STARTED,
    STAGE_RUN_COMPLETED,
    STAGE_RUN_FAILED,
)
from .run_context import (
    ExpertResult,
    OrchestratorMessage,
    Plan,
    RunContext,
    StateTransition,
)
from .state_machine import (
    ALL_STATES,
    ORCHESTRATOR_STATE_AGGREGATING,
    ORCHESTRATOR_STATE_COMPLETED,
    ORCHESTRATOR_STATE_DELEGATING,
    ORCHESTRATOR_STATE_FAILED,
    ORCHESTRATOR_STATE_PLANNING,
    ORCHESTRATOR_STATE_RECEIVED,
    TERMINAL_STATES,
    TRANSITIONS,
    OrchestratorStateMachine,
)

__all__ = [
    "Aggregator",
    "AggregatorConfig",
    "AggregatorError",
    "Delegator",
    "DelegatorConfig",
    "DictAgentProvider",
    "ExpertInvocation",
    "ExpertInvocationError",
    "ExpertInvoker",
    "InMemoryBackend",
    "InboundHandler",
    "InboundHandlerConfig",
    "InboundMessage",
    "InboundRequest",
    "InboundResponse",
    "LLMCall",
    "LLMResponse",
    "MetricsBackend",
    "NoopRecorder",
    "NoopRun",
    "NoopStage",
    "OrchestratorError",
    "OrchestratorMetrics",
    "OrchestratorStateError",
    "OrchestratorEvent",
    "PHIRedactionError",
    "PHIRedactionResult",
    "PHIRedactor",
    "Planner",
    "PlannerConfig",
    "PlannerError",
    "ExpertResult",
    "OrchestratorMessage",
    "Plan",
    "RecorderAdapter",
    "RecorderLike",
    "RunContext",
    "STAGE_AGGREGATED",
    "STAGE_AGGREGATING_STARTED",
    "STAGE_DELEGATING_STARTED",
    "STAGE_EXPERT_INVOKED",
    "STAGE_EXPERT_RETURNED",
    "STAGE_INBOUND_RECEIVED",
    "STAGE_PHI_REDACTED",
    "STAGE_PLAN_GENERATED",
    "STAGE_PLANNING_STARTED",
    "STAGE_RUN_COMPLETED",
    "STAGE_RUN_FAILED",
    "StateTransition",
    "ALL_STATES",
    "NON_GOALS_NOTICE",
    "ORCHESTRATOR_STATE_AGGREGATING",
    "ORCHESTRATOR_STATE_COMPLETED",
    "ORCHESTRATOR_STATE_DELEGATING",
    "ORCHESTRATOR_STATE_FAILED",
    "ORCHESTRATOR_STATE_PLANNING",
    "ORCHESTRATOR_STATE_RECEIVED",
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "PHI_REDACTION_NOTICE",
    "PLAN_SCHEMA_DESCRIPTION",
    "PRODUCTION_WRITEBACK_BLOCKED",
    "TERMINAL_STATES",
    "TRANSITIONS",
    "OrchestratorStateMachine",
    "assert_prompt_invariants",
    "build_planner_user_message",
    "build_planner_user_message_from_agent",
    "extract_text_from_parts",
    "get_metrics",
    "is_valid_request",
    "make_context_id",
    "make_message_id",
    "make_run_id",
    "reset_default_metrics",
]
