"""001_initial_all_tables

Revision ID: afeb04d02665
Revises: 
Create Date: 2026-05-18 11:55:50.126037

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'afeb04d02665'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('expert_ids', sa.JSON(), nullable=False),
    sa.Column('default_expert_id', sa.String(length=12), nullable=False),
    sa.Column('a2a_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_prebuilt', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_category'), 'agents', ['category'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_input_summary', sa.Text(), nullable=True),
    sa.Column('model_output_summary', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('tool_calls_made', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('code_mappings',
    sa.Column('source_table_id', sa.String(length=12), nullable=False),
    sa.Column('target_table_id', sa.String(length=12), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('target_code', sa.String(length=64), nullable=False),
    sa.Column('target_name', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mapping_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_mappings_source_code'), 'code_mappings', ['source_code'], unique=False)
    op.create_index(op.f('ix_code_mappings_source_table_id'), 'code_mappings', ['source_table_id'], unique=False)
    op.create_index(op.f('ix_code_mappings_target_table_id'), 'code_mappings', ['target_table_id'], unique=False)
    op.create_table('code_tables',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code_system', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('institution', sa.String(length=256), nullable=False),
    sa.Column('total_codes', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_tables_code_system'), 'code_tables', ['code_system'], unique=False)
    op.create_index(op.f('ix_code_tables_name'), 'code_tables', ['name'], unique=False)
    op.create_table('encounters',
    sa.Column('encounter_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('admission_time', sa.DateTime(), nullable=True),
    sa.Column('discharge_time', sa.DateTime(), nullable=True),
    sa.Column('admission_reason', sa.Text(), nullable=True),
    sa.Column('discharge_summary', sa.Text(), nullable=True),
    sa.Column('existing_diagnosis_codes', sa.JSON(), nullable=False),
    sa.Column('existing_procedure_codes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_encounter_id'), 'encounters', ['encounter_id'], unique=True)
    op.create_table('experts',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_prebuilt', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_category'), 'experts', ['category'], unique=False)
    op.create_index(op.f('ix_experts_name'), 'experts', ['name'], unique=False)
    op.create_table('gold_cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('diagnosis_group', sa.String(length=128), nullable=False),
    sa.Column('original_primary_diagnosis', sa.String(length=32), nullable=False),
    sa.Column('original_primary_diag_name', sa.String(length=256), nullable=False),
    sa.Column('original_main_procedure', sa.String(length=32), nullable=True),
    sa.Column('original_main_proc_name', sa.String(length=256), nullable=True),
    sa.Column('expected_principal_diagnosis', sa.String(length=32), nullable=False),
    sa.Column('expected_principal_diag_name', sa.String(length=256), nullable=False),
    sa.Column('expected_principal_procedure', sa.String(length=32), nullable=True),
    sa.Column('expected_principal_proc_name', sa.String(length=256), nullable=True),
    sa.Column('expected_secondary_diagnoses', sa.JSON(), nullable=True),
    sa.Column('expected_procedure_codes', sa.JSON(), nullable=True),
    sa.Column('expected_drg_group', sa.String(length=16), nullable=True),
    sa.Column('acceptable_alternatives', sa.JSON(), nullable=True),
    sa.Column('reasoning_expectations', sa.JSON(), nullable=True),
    sa.Column('missing_codes', sa.JSON(), nullable=True),
    sa.Column('unsupported_codes', sa.JSON(), nullable=True),
    sa.Column('documentation_gaps', sa.JSON(), nullable=True),
    sa.Column('evidence_spans', sa.JSON(), nullable=True),
    sa.Column('full_case_data', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('risk_tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=True),
    sa.Column('review_time', sa.String(length=32), nullable=True),
    sa.Column('agent_accuracy', sa.Float(), nullable=True),
    sa.Column('last_evaluated_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_cases_case_id'), 'gold_cases', ['case_id'], unique=True)
    op.create_table('oauth_clients',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scopes', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(length=12), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('token_expires_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth_clients_owner_id'), 'oauth_clients', ['owner_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('scopes', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_oauth_tokens_client_id'), 'oauth_tokens', ['client_id'], unique=False)
    op.create_table('runtime_sessions',
    sa.Column('runtime_id', sa.String(length=64), nullable=False, comment='Unique runtime identifier (matches pipeline_id / run_id)'),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False, comment='Pipeline or Agent run identifier'),
    sa.Column('review_id', sa.String(length=64), nullable=True, comment='Linked CodingReview.review_id if applicable'),
    sa.Column('agent_id', sa.String(length=64), nullable=True, comment='Linked Agent.id if AgentRunner path'),
    sa.Column('current_state', sa.String(length=32), nullable=False, comment='Current CaseState value'),
    sa.Column('previous_state', sa.String(length=32), nullable=True, comment='Previous state before last transition'),
    sa.Column('state_entered_at', sa.DateTime(), nullable=False, comment='When current_state was entered (for timeout calculation)'),
    sa.Column('timeout_at', sa.DateTime(), nullable=True, comment='When the current state will timeout (derived from STATE_TIMEOUTS)'),
    sa.Column('escalated', sa.Boolean(), nullable=False, comment='True if this runtime has been escalated to supervisor'),
    sa.Column('escalated_at', sa.DateTime(), nullable=True, comment='When escalation occurred'),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('execution_path', sa.String(length=32), nullable=False, comment='Which execution path: orchestrator | agent_runner | intelligent'),
    sa.Column('total_processing_ms', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=True, comment='SHA-256 hash of key fields for tamper detection'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_sessions_agent_id'), 'runtime_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_runtime_sessions_current_state'), 'runtime_sessions', ['current_state'], unique=False)
    op.create_index(op.f('ix_runtime_sessions_pipeline_id'), 'runtime_sessions', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_runtime_sessions_review_id'), 'runtime_sessions', ['review_id'], unique=False)
    op.create_index(op.f('ix_runtime_sessions_runtime_id'), 'runtime_sessions', ['runtime_id'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CODER', 'DEPT_HEAD', 'INSURANCE', 'QC', 'CLINICIAN', 'IT', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('owner_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_owner_id'), 'api_keys', ['owner_id'], unique=False)
    op.create_table('coding_reviews',
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=12), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('primary_diagnosis_code', sa.String(length=32), nullable=True),
    sa.Column('primary_diagnosis_name', sa.String(length=256), nullable=True),
    sa.Column('primary_diagnosis_confidence', sa.Float(), nullable=False),
    sa.Column('primary_diagnosis_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('primary_diagnosis_judgment', sa.Enum('SUPPORTED', 'UNSUPPORTED', 'NEEDS_REVIEW', 'REJECTED', 'CONFIRMED', name='reviewjudgment'), nullable=False),
    sa.Column('primary_diagnosis_reasoning', sa.JSON(), nullable=True),
    sa.Column('main_procedure_code', sa.String(length=32), nullable=True),
    sa.Column('main_procedure_name', sa.String(length=256), nullable=True),
    sa.Column('main_procedure_confidence', sa.Float(), nullable=False),
    sa.Column('main_procedure_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('main_procedure_judgment', sa.Enum('SUPPORTED', 'UNSUPPORTED', 'NEEDS_REVIEW', 'REJECTED', 'CONFIRMED', name='reviewjudgment'), nullable=False),
    sa.Column('secondary_diagnoses', sa.JSON(), nullable=True),
    sa.Column('other_procedures', sa.JSON(), nullable=True),
    sa.Column('diagnosis_analysis', sa.JSON(), nullable=True),
    sa.Column('procedure_analysis', sa.JSON(), nullable=True),
    sa.Column('documentation_gaps', sa.JSON(), nullable=True),
    sa.Column('uncodable_items', sa.JSON(), nullable=True),
    sa.Column('drg_impact', sa.JSON(), nullable=True),
    sa.Column('human_checklist', sa.JSON(), nullable=True),
    sa.Column('validation_summary', sa.JSON(), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('human_review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.String(length=64), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_reviews_encounter_id'), 'coding_reviews', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_coding_reviews_review_id'), 'coding_reviews', ['review_id'], unique=True)
    op.create_table('conversation_memories',
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('expert_id', sa.String(length=12), nullable=True),
    sa.Column('agent_id', sa.String(length=12), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('key_facts', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memories_agent_id'), 'conversation_memories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversation_memories_expert_id'), 'conversation_memories', ['expert_id'], unique=False)
    op.create_index(op.f('ix_conversation_memories_session_id'), 'conversation_memories', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_memories_user_id'), 'conversation_memories', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('encounter_id', sa.String(length=12), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('doc_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_encounter_id'), 'documents', ['encounter_id'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('expert_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('transport_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('auth_header', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_servers_expert_id'), 'mcp_servers', ['expert_id'], unique=False)
    op.create_table('runtime_audit_records',
    sa.Column('runtime_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='state_transition | guard_check | post_guard | human_confirmation | timeout_escalation | illegal_transition_attempt | forced_transition'),
    sa.Column('action', sa.String(length=128), nullable=True, comment='The action being guarded/executed'),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('current_state', sa.String(length=32), nullable=True, comment='Runtime state at time of event'),
    sa.Column('guard_result', sa.String(length=16), nullable=True, comment='ALLOW | REVIEW | DENY | DEFER'),
    sa.Column('post_check_result', sa.String(length=16), nullable=True, comment='ALLOW | REVIEW | DENY (for guard_post)'),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('immutable_hash', sa.String(length=32), nullable=True, comment='SHA-256 hash of (event_type + action + actor + payload) — proves this record has not been modified'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['runtime_id'], ['runtime_sessions.runtime_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_audit_records_event_type'), 'runtime_audit_records', ['event_type'], unique=False)
    op.create_index(op.f('ix_runtime_audit_records_runtime_id'), 'runtime_audit_records', ['runtime_id'], unique=False)
    op.create_table('runtime_duc_decisions',
    sa.Column('runtime_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False, comment='DUC action name (must be in DUC_ACTIONS set)'),
    sa.Column('reviewer', sa.String(length=128), nullable=False, comment='Username or full name of the human reviewer'),
    sa.Column('decision', sa.String(length=32), nullable=False, comment='approved | rejected'),
    sa.Column('reason', sa.Text(), nullable=True, comment="Reviewer's rationale"),
    sa.Column('current_state', sa.String(length=32), nullable=True, comment='Runtime state when decision was made'),
    sa.Column('decision_hash', sa.String(length=32), nullable=True, comment='SHA-256 hash for immutability'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['runtime_id'], ['runtime_sessions.runtime_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_duc_decisions_action'), 'runtime_duc_decisions', ['action'], unique=False)
    op.create_index(op.f('ix_runtime_duc_decisions_runtime_id'), 'runtime_duc_decisions', ['runtime_id'], unique=False)
    op.create_table('runtime_transitions',
    sa.Column('runtime_id', sa.String(length=64), nullable=False, comment='Parent RuntimeSession'),
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('transition_type', sa.String(length=32), nullable=False, comment='normal | forced | timeout | recovery'),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('payload_hash', sa.String(length=32), nullable=True, comment='SHA-256 of payload for integrity verification'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['runtime_id'], ['runtime_sessions.runtime_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_transitions_from_state'), 'runtime_transitions', ['from_state'], unique=False)
    op.create_index(op.f('ix_runtime_transitions_runtime_id'), 'runtime_transitions', ['runtime_id'], unique=False)
    op.create_index(op.f('ix_runtime_transitions_to_state'), 'runtime_transitions', ['to_state'], unique=False)
    op.create_table('team_invites',
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CODER', 'DEPT_HEAD', 'VIEWER', name='teamrole'), nullable=False),
    sa.Column('invited_by', sa.String(length=12), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_team_invites_email'), 'team_invites', ['email'], unique=False)
    op.create_table('team_members',
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'CODER', 'DEPT_HEAD', 'VIEWER', name='teamrole'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invited_by', sa.String(length=12), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('clinical_evidences',
    sa.Column('review_id', sa.String(length=12), nullable=False),
    sa.Column('doc_id', sa.String(length=12), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('supports_codes', sa.JSON(), nullable=False),
    sa.Column('certainty', sa.String(length=32), nullable=False),
    sa.Column('negation', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['coding_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_evidences_review_id'), 'clinical_evidences', ['review_id'], unique=False)
    op.create_table('code_candidates',
    sa.Column('review_id', sa.String(length=12), nullable=False),
    sa.Column('finding', sa.String(length=512), nullable=False),
    sa.Column('code_system', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('chapter', sa.String(length=256), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rule_checks', sa.JSON(), nullable=True),
    sa.Column('human_decision', sa.String(length=32), nullable=True),
    sa.Column('human_reason', sa.String(length=512), nullable=True),
    sa.Column('modified_code', sa.String(length=32), nullable=True),
    sa.Column('modified_name', sa.String(length=256), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['coding_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_candidates_review_id'), 'code_candidates', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_candidates_review_id'), table_name='code_candidates')
    op.drop_table('code_candidates')
    op.drop_index(op.f('ix_clinical_evidences_review_id'), table_name='clinical_evidences')
    op.drop_table('clinical_evidences')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_team_invites_email'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_index(op.f('ix_runtime_transitions_to_state'), table_name='runtime_transitions')
    op.drop_index(op.f('ix_runtime_transitions_runtime_id'), table_name='runtime_transitions')
    op.drop_index(op.f('ix_runtime_transitions_from_state'), table_name='runtime_transitions')
    op.drop_table('runtime_transitions')
    op.drop_index(op.f('ix_runtime_duc_decisions_runtime_id'), table_name='runtime_duc_decisions')
    op.drop_index(op.f('ix_runtime_duc_decisions_action'), table_name='runtime_duc_decisions')
    op.drop_table('runtime_duc_decisions')
    op.drop_index(op.f('ix_runtime_audit_records_runtime_id'), table_name='runtime_audit_records')
    op.drop_index(op.f('ix_runtime_audit_records_event_type'), table_name='runtime_audit_records')
    op.drop_table('runtime_audit_records')
    op.drop_index(op.f('ix_mcp_servers_expert_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_documents_encounter_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversation_memories_user_id'), table_name='conversation_memories')
    op.drop_index(op.f('ix_conversation_memories_session_id'), table_name='conversation_memories')
    op.drop_index(op.f('ix_conversation_memories_expert_id'), table_name='conversation_memories')
    op.drop_index(op.f('ix_conversation_memories_agent_id'), table_name='conversation_memories')
    op.drop_table('conversation_memories')
    op.drop_index(op.f('ix_coding_reviews_review_id'), table_name='coding_reviews')
    op.drop_index(op.f('ix_coding_reviews_encounter_id'), table_name='coding_reviews')
    op.drop_table('coding_reviews')
    op.drop_index(op.f('ix_api_keys_owner_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_runtime_sessions_runtime_id'), table_name='runtime_sessions')
    op.drop_index(op.f('ix_runtime_sessions_review_id'), table_name='runtime_sessions')
    op.drop_index(op.f('ix_runtime_sessions_pipeline_id'), table_name='runtime_sessions')
    op.drop_index(op.f('ix_runtime_sessions_current_state'), table_name='runtime_sessions')
    op.drop_index(op.f('ix_runtime_sessions_agent_id'), table_name='runtime_sessions')
    op.drop_table('runtime_sessions')
    op.drop_index(op.f('ix_oauth_tokens_client_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_oauth_clients_owner_id'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_gold_cases_case_id'), table_name='gold_cases')
    op.drop_table('gold_cases')
    op.drop_index(op.f('ix_experts_name'), table_name='experts')
    op.drop_index(op.f('ix_experts_category'), table_name='experts')
    op.drop_table('experts')
    op.drop_index(op.f('ix_encounters_encounter_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_code_tables_name'), table_name='code_tables')
    op.drop_index(op.f('ix_code_tables_code_system'), table_name='code_tables')
    op.drop_table('code_tables')
    op.drop_index(op.f('ix_code_mappings_target_table_id'), table_name='code_mappings')
    op.drop_index(op.f('ix_code_mappings_source_table_id'), table_name='code_mappings')
    op.drop_index(op.f('ix_code_mappings_source_code'), table_name='code_mappings')
    op.drop_table('code_mappings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_category'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
