"""Corti §13.4 Guided Templates + Sections — list shape (Cycle 4).

Cycle 4 (2026-07-01) — LIST endpoints only for the simplest read path
that an SDK caller needs to discover available templates/sections. Full
CRUD (create/update/delete + version publish) lands in a later cycle.

Spec sources:
- ``docs/corti-reverse-engineered/guided-templates-list.md`` (23,529 bytes,
  fetched 2026-07-01 from
  ``https://docs.corti.ai/api-reference/guided-templates/list-templates.md``).
  Path: ``GET /documents/templates/`` → operationId ``guided_templates_list``.
- ``docs/corti-reverse-engineered/guided-sections-list.md`` (18,630 bytes,
  fetched 2026-07-01 from
  ``https://docs.corti.ai/api-reference/guided-sections/list-sections.md``).
  Path: ``GET /documents/sections/`` → operationId ``guided_sections_list``.

Cycle 4 deliberately closes **only the read path**. The two
``GuidedTemplate`` / ``GuidedSection`` shapes share the same top-level
required field set (id, name, languages, regions, specialties, labels,
createdAt, updatedAt) and the same optional extension fields
(inheritedFromId, autoGenerated, source, description, publishedVersion,
createdBy, deletedAt) — so a single shared sub-schema definition is
sufficient for list responses.

The published-version sub-schemas (``GuidedTemplateVersion`` /
``GuidedSectionVersion``) are intentionally NOT wired here because the
Cycle 4 stub data does not include a published version. Wire-up happens
when a real publish endpoint lands in a follow-on cycle.
"""

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


# ─── Shared sub-schemas ──────────────────────────────────────────────


class GuidedLabel(BaseModel):
    """``GuidedLabel`` schema — key/value tag, shared with cycle 3.

    Required: ``key``, ``value``. Used as both a labels-list element and as
    a query-param filter token (``key:value``) in the LIST endpoints.
    """
    key: str = Field(..., min_length=1)
    value: str = Field(..., min_length=1)


# ─── GuidedTemplate (list shape) ────────────────────────────────────


class GuidedTemplate(BaseModel):
    """``GuidedTemplate`` schema — list-shape fields only.

    Cycle 4 returns templates WITHOUT ``publishedVersion`` (the stub data
    does not yet host a published version). Once a publish endpoint
    lands, ``publishedVersion`` will be populated for templates that have
    a published version and omitted otherwise.
    """
    id: str = Field(..., description="UUID of the template")
    inheritedFromId: Optional[str] = Field(
        default=None, description="UUID of the inherited-from template (nullable)"
    )
    autoGenerated: Optional[bool] = Field(
        default=None, description="True if auto-generated from a section-composed POST"
    )
    source: Optional[Literal["user", "corti", "project"]] = Field(
        default=None, description="Content source: user-created / Corti standard / project"
    )
    name: str = Field(..., min_length=1)
    description: Optional[str] = Field(default=None, description="Human-readable description")
    languages: List[str] = Field(
        default_factory=list, description="BCP 47 language tags with tweaks"
    )
    regions: List[str] = Field(
        default_factory=list, description="ISO 3166-1 alpha-3 region codes with tweaks"
    )
    specialties: List[str] = Field(
        default_factory=list, description="Clinical specialties with tweaks"
    )
    labels: List[GuidedLabel] = Field(default_factory=list)
    createdBy: Optional[str] = Field(default=None, description="UUID of the creator")
    createdAt: str = Field(..., description="ISO 8601 timestamp of creation")
    updatedAt: str = Field(..., description="ISO 8601 timestamp of last update")
    deletedAt: Optional[str] = Field(
        default=None, description="ISO 8601 timestamp of soft-delete (nullable)"
    )


# ─── GuidedSection (list shape) ─────────────────────────────────────


class GuidedSection(BaseModel):
    """``GuidedSection`` schema — list-shape fields only.

    Same top-level structure as ``GuidedTemplate`` for parity with the
    Corti OpenAPI spec. The deeper nested generation / output schema
    types (GuidedOutputSchema, GuidedStringNode, etc.) are not surfaced
    in Cycle 4 because the stub data doesn't include them.
    """
    id: str = Field(..., description="UUID of the section")
    inheritedFromId: Optional[str] = Field(
        default=None, description="UUID of the inherited-from section (nullable)"
    )
    autoGenerated: Optional[bool] = Field(
        default=None, description="True if auto-generated from inline POST /documents"
    )
    source: Optional[Literal["user", "corti", "project"]] = Field(
        default=None, description="Content source: user-created / Corti standard / project"
    )
    name: str = Field(..., min_length=1)
    languages: List[str] = Field(
        default_factory=list, description="BCP 47 language tags with tweaks"
    )
    regions: List[str] = Field(
        default_factory=list, description="ISO 3166-1 alpha-3 region codes with tweaks"
    )
    specialties: List[str] = Field(
        default_factory=list, description="Clinical specialties with tweaks"
    )
    description: Optional[str] = Field(default=None)
    labels: List[GuidedLabel] = Field(default_factory=list)
    createdBy: Optional[str] = Field(default=None, description="UUID of the creator")
    createdAt: str = Field(..., description="ISO 8601 timestamp of creation")
    updatedAt: str = Field(..., description="ISO 8601 timestamp of last update")
    deletedAt: Optional[str] = Field(
        default=None, description="ISO 8601 timestamp of soft-delete (nullable)"
    )