"""Corti Guided Templates + Sections discovery shapes.

The same projections are used for collection discovery and single-resource
reads. Tenant-owned Builder mutations remain on the product ``/api/templates``
surface because Corti's public documentation currently exposes list/get while
describing API-side template creation/management as roadmap work.

Spec sources:
- ``docs/corti-reverse-engineered/guided-templates-list.md`` (23,529 bytes,
  fetched 2026-07-01 from
  ``https://docs.corti.ai/api-reference/guided-templates/list-templates.md``).
  Path: ``GET /documents/templates/`` → operationId ``guided_templates_list``.
- ``docs/corti-reverse-engineered/guided-sections-list.md`` (18,630 bytes,
  fetched 2026-07-01 from
  ``https://docs.corti.ai/api-reference/guided-sections/list-sections.md``).
  Path: ``GET /documents/sections/`` → operationId ``guided_sections_list``.

The current implementation closes the authenticated read path. The two
``GuidedTemplate`` / ``GuidedSection`` shapes share the same top-level
required field set (id, name, languages, regions, specialties, labels,
createdAt, updatedAt) and the same optional extension fields
(inheritedFromId, autoGenerated, source, description, publishedVersion,
createdBy, deletedAt) — so a single shared sub-schema definition is
sufficient for list responses.

Published versions are immutable snapshots created by the tenant Builder and
use Corti's documented ``id`` / ``versionNumber`` / ``generation`` contract.
"""

from __future__ import annotations

from typing import Any, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


# ─── Shared sub-schemas ──────────────────────────────────────────────


class GuidedLabel(BaseModel):
    """``GuidedLabel`` schema — key/value tag, shared with cycle 3.

    Required: ``key``, ``value``. Used as both a labels-list element and as
    a query-param filter token (``key:value``) in the LIST endpoints.
    """
    key: str = Field(..., min_length=1)
    value: str = Field(..., min_length=1)


class GuidedTemplateVersion(BaseModel):
    """Currently published immutable template version."""

    id: str
    versionNumber: int = Field(..., ge=0)
    generation: dict[str, Any]
    deletedAt: Optional[str] = None


# ─── GuidedTemplate (list shape) ────────────────────────────────────


class GuidedTemplate(BaseModel):
    """``GuidedTemplate`` schema — list-shape fields only.

    ``publishedVersion`` is populated for product-managed built-ins and for
    tenant drafts that have passed through the explicit publish endpoint.
    """
    id: str = Field(..., description="UUID of the template")
    inheritedFromId: Optional[str] = Field(
        default=None, description="UUID of the inherited-from template (nullable)"
    )
    autoGenerated: Optional[bool] = Field(
        default=None, description="True if auto-generated from a section-composed POST"
    )
    source: Optional[Literal["user", "corti", "project"]] = Field(
        default=None, description="Content source: user-created / Corti standard / project"
    )
    name: str = Field(..., min_length=1)
    description: Optional[str] = Field(default=None, description="Human-readable description")
    languages: List[str] = Field(
        default_factory=list, description="BCP 47 language tags with tweaks"
    )
    regions: List[str] = Field(
        default_factory=list, description="ISO 3166-1 alpha-3 region codes with tweaks"
    )
    specialties: List[str] = Field(
        default_factory=list, description="Clinical specialties with tweaks"
    )
    labels: List[GuidedLabel] = Field(default_factory=list)
    publishedVersion: Optional[GuidedTemplateVersion] = None
    createdBy: Optional[str] = Field(default=None, description="UUID of the creator")
    createdAt: str = Field(..., description="ISO 8601 timestamp of creation")
    updatedAt: str = Field(..., description="ISO 8601 timestamp of last update")
    deletedAt: Optional[str] = Field(
        default=None, description="ISO 8601 timestamp of soft-delete (nullable)"
    )


# ─── GuidedSection (list shape) ─────────────────────────────────────


class GuidedSection(BaseModel):
    """``GuidedSection`` schema — list-shape fields only.

    The list-compatible metadata is supplemented with the current immutable
    version ID and resolved generation definition so the local Builder can
    compose a durable template without invoking an LLM.
    """
    id: str = Field(..., description="UUID of the section")
    inheritedFromId: Optional[str] = Field(
        default=None, description="UUID of the inherited-from section (nullable)"
    )
    autoGenerated: Optional[bool] = Field(
        default=None, description="True if auto-generated from inline POST /documents"
    )
    versionId: Optional[str] = Field(
        default=None, description="Current immutable section version identifier"
    )
    generation: Optional[dict[str, Any]] = Field(
        default=None, description="Resolved generation definition for Builder composition"
    )
    source: Optional[Literal["user", "corti", "project"]] = Field(
        default=None, description="Content source: user-created / Corti standard / project"
    )
    name: str = Field(..., min_length=1)
    languages: List[str] = Field(
        default_factory=list, description="BCP 47 language tags with tweaks"
    )
    regions: List[str] = Field(
        default_factory=list, description="ISO 3166-1 alpha-3 region codes with tweaks"
    )
    specialties: List[str] = Field(
        default_factory=list, description="Clinical specialties with tweaks"
    )
    description: Optional[str] = Field(default=None)
    labels: List[GuidedLabel] = Field(default_factory=list)
    createdBy: Optional[str] = Field(default=None, description="UUID of the creator")
    createdAt: str = Field(..., description="ISO 8601 timestamp of creation")
    updatedAt: str = Field(..., description="ISO 8601 timestamp of last update")
    deletedAt: Optional[str] = Field(
        default=None, description="ISO 8601 timestamp of soft-delete (nullable)"
    )


class GuidedSectionCreate(BaseModel):
    """iCoDer Console extension for creating a tenant-owned section."""

    name: str = Field(..., min_length=1, max_length=256)
    description: str = Field(default="", max_length=4096)
    language: str = Field(default="zh-CN", min_length=2, max_length=32)
    specialties: List[str] = Field(default_factory=lambda: ["custom"], max_length=20)
    labels: List[GuidedLabel] = Field(default_factory=list, max_length=50)
    outputSchema: dict[str, Any] = Field(default_factory=lambda: {"type": "string"})

    @field_validator("name", "language")
    @classmethod
    def _required_text_not_blank(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("value must not be blank")
        return value


class GuidedSectionUpdate(BaseModel):
    """Partial update for a tenant-owned section; nulls are rejected."""

    name: Optional[str] = Field(default=None, min_length=1, max_length=256)
    description: Optional[str] = Field(default=None, max_length=4096)
    language: Optional[str] = Field(default=None, min_length=2, max_length=32)
    specialties: Optional[List[str]] = Field(default=None, max_length=20)
    labels: Optional[List[GuidedLabel]] = Field(default=None, max_length=50)
    outputSchema: Optional[dict[str, Any]] = None

    @field_validator("name", "language")
    @classmethod
    def _updated_text_not_blank(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return value
        value = value.strip()
        if not value:
            raise ValueError("value must not be blank")
        return value

    @model_validator(mode="after")
    def _require_non_null_change(self) -> "GuidedSectionUpdate":
        if not self.model_fields_set:
            raise ValueError("at least one section field must be provided")
        if any(getattr(self, field) is None for field in self.model_fields_set):
            raise ValueError("section update fields must not be null")
        return self
