import type { AxiosInstance } from 'axios';
import { requestConfig, type iCoDerRequestOptions } from '../request-options.js';

export interface GuidedLabel { key: string; value: string }

export interface GuidedTemplateVersion {
  id: string;
  versionNumber: number;
  generation: Record<string, unknown>;
  deletedAt: string | null;
}

export interface GuidedTemplate {
  id: string;
  inheritedFromId: string | null;
  autoGenerated: boolean | null;
  source: 'user' | 'corti' | 'project' | null;
  name: string;
  description: string;
  languages: string[];
  regions: string[];
  specialties: string[];
  labels: GuidedLabel[];
  publishedVersion: GuidedTemplateVersion | null;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

export interface GuidedSection extends Omit<GuidedTemplate, 'description'> {
  description: string | null;
  versionId: string | null;
  generation: Record<string, unknown> | null;
}

export interface GuidedDiscoveryFilters {
  lang?: string[];
  region?: string[];
  specialty?: string[];
  label?: string[];
  published?: boolean;
  source?: 'user' | 'corti' | 'project';
}

export interface SectionMutation {
  name: string;
  description?: string;
  language?: string;
  specialties?: string[];
  labels?: GuidedLabel[];
  outputSchema?: Record<string, unknown>;
}

function discoveryParams(filters: GuidedDiscoveryFilters): URLSearchParams {
  const params = new URLSearchParams();
  for (const key of ['lang', 'region', 'specialty', 'label'] as const) {
    for (const value of filters[key] || []) params.append(key, value);
  }
  if (filters.published !== undefined) params.set('published', String(filters.published));
  if (filters.source) params.set('source', filters.source);
  return params;
}

export class TemplatesResource {
  constructor(private readonly http: AxiosInstance) {}

  async list(
    filters: GuidedDiscoveryFilters = {},
    options?: iCoDerRequestOptions,
  ): Promise<GuidedTemplate[]> {
    const { data } = await this.http.get<GuidedTemplate[]>(
      '/api/v2/tools/templates/',
      requestConfig(options, discoveryParams(filters)),
    );
    return data;
  }

  async get(templateId: string, options?: iCoDerRequestOptions): Promise<GuidedTemplate> {
    const { data } = await this.http.get<GuidedTemplate>(
      `/api/v2/tools/templates/${encodeURIComponent(templateId)}`,
      requestConfig(options),
    );
    return data;
  }

  async publish(
    templateId: string,
    options?: iCoDerRequestOptions,
  ): Promise<GuidedTemplateVersion> {
    const { data } = await this.http.post<GuidedTemplateVersion>(
      `/api/v2/tools/templates/${encodeURIComponent(templateId)}/publish`,
      undefined,
      requestConfig(options),
    );
    return data;
  }

  async listSections(
    filters: GuidedDiscoveryFilters = {},
    options?: iCoDerRequestOptions,
  ): Promise<GuidedSection[]> {
    const { data } = await this.http.get<GuidedSection[]>(
      '/api/v2/tools/sections/',
      requestConfig(options, discoveryParams(filters)),
    );
    return data;
  }

  async getSection(sectionId: string, options?: iCoDerRequestOptions): Promise<GuidedSection> {
    const { data } = await this.http.get<GuidedSection>(
      `/api/v2/tools/sections/${encodeURIComponent(sectionId)}`,
      requestConfig(options),
    );
    return data;
  }

  async createSection(
    request: SectionMutation,
    options?: iCoDerRequestOptions,
  ): Promise<GuidedSection> {
    const { data } = await this.http.post<GuidedSection>(
      '/api/v2/tools/sections/', request, requestConfig(options),
    );
    return data;
  }

  async updateSection(
    sectionId: string,
    request: Partial<SectionMutation>,
    options?: iCoDerRequestOptions,
  ): Promise<GuidedSection> {
    const { data } = await this.http.patch<GuidedSection>(
      `/api/v2/tools/sections/${encodeURIComponent(sectionId)}`,
      request,
      requestConfig(options),
    );
    return data;
  }

  async deleteSection(sectionId: string, options?: iCoDerRequestOptions): Promise<void> {
    await this.http.delete(
      `/api/v2/tools/sections/${encodeURIComponent(sectionId)}`,
      requestConfig(options),
    );
  }
}
