// iCoDer - Templates (Beta) page
//
// IA:
//   Header  Templates · "Manage templates and sections for generating
//           structured documents"
//   CTA     Template builder (right-aligned, opens builder modal)
//   Banner  "Templates (beta) is powered by the new templates and
//           sections API" + working support route
//   View    Templates / Sections (both backed by tenant-scoped APIs)
//   Filters Search + Language combobox + All types + Filter
//   Cards   Name + Description · builtin badge · scope badge · 3-dot menu
//
// iCoDer extension: Templates seeded with 9 Chinese clinical templates
// (inpatient / surgery / outpatient / emergency / consultation) so users
// see a real library out of the box; CN-language combobox default.
import { useEffect, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Loader2, Plus, Search, X, ExternalLink, FileText, MoreVertical,
  Sparkles, MessageSquareWarning,
} from 'lucide-react';

import { templatesApi } from '../services/api';
import { useT } from '../i18n';

interface Template {
  id: string;
  name: string;
  description: string;
  content: string;
  category: string;
  language: string;
  is_builtin: boolean;
  scope: string;
  created_at: string | null;
  updated_at: string | null;
  published_version_count: number;
  published_version: {
    id: string;
    version_number: number;
    created_at: string | null;
  } | null;
}

interface GuidedSection {
  id: string;
  name: string;
  description: string | null;
  source: 'user' | 'corti' | 'project' | null;
  createdBy: string | null;
  autoGenerated: boolean | null;
  versionId: string | null;
  generation: {
    sectionId?: string;
    sectionVersionId?: string;
    heading: string;
    instructions: { contentPrompt: string; writingStylePrompt?: string; miscPrompt?: string };
    outputSchema: Record<string, unknown>;
  } | null;
  languages: string[];
  regions: string[];
  specialties: string[];
  labels: Array<{ key: string; value: string }>;
}

type View = 'templates' | 'sections';
type CategoryFilter = '' | 'inpatient' | 'surgery' | 'outpatient' | 'emergency' | 'consultation' | 'custom';
type LanguageFilter = '' | 'zh-CN' | 'en-US';
type SortKey = 'recent' | 'name';

const CATEGORY_LABEL_KEY: Record<string, string> = {
  inpatient: 'templateCategoryInpatient',
  surgery: 'templateCategorySurgery',
  outpatient: 'templateCategoryOutpatient',
  emergency: 'templateCategoryEmergency',
  consultation: 'templateCategoryConsultation',
  custom: 'templateCategoryCustom',
};

export default function TemplatesPage() {
  const navigate = useNavigate();
  const t = useT();
  const [view, setView] = useState<View>('templates');
  const [items, setItems] = useState<Template[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState<CategoryFilter>('');
  const [language, setLanguage] = useState<LanguageFilter>('');
  const [page, setPage] = useState(1);
  const [showBuilder, setShowBuilder] = useState(false);
  const [editingTemplate, setEditingTemplate] = useState<Template | null>(null);
  const [sections, setSections] = useState<GuidedSection[]>([]);
  const [sectionsLoading, setSectionsLoading] = useState(false);
  const [sectionsError, setSectionsError] = useState('');
  const [showSectionEditor, setShowSectionEditor] = useState(false);
  const [editingSection, setEditingSection] = useState<GuidedSection | null>(null);

  const fetchList = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const res = await templatesApi.list({
        search: search.trim(),
        category,
        language,
        page,
        page_size: 50, // Templates Beta is a content library, not a heavy table
      });
      setItems(res.data.templates || []);
      setTotal(res.data.total || 0);
    } catch (err: any) {
      setError(err?.response?.data?.detail?.message || err?.message || '加载模板失败');
    } finally {
      setLoading(false);
    }
  }, [search, category, language, page]);

  useEffect(() => { fetchList(); }, [fetchList]);
  useEffect(() => { setPage(1); }, [search, category, language]);
  const fetchSections = useCallback(async () => {
    setSectionsLoading(true);
    setSectionsError('');
    try {
      const response = await templatesApi.sections();
      setSections(response.data || []);
    } catch (err: any) {
      setSectionsError(err?.response?.data?.detail?.message || err?.message || '加载章节失败');
    } finally {
      setSectionsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (view === 'sections') fetchSections();
  }, [view, fetchSections]);

  const visibleSections = sections.filter(section => {
    const query = search.trim().toLocaleLowerCase();
    const matchesSearch = !query || `${section.name} ${section.description || ''}`.toLocaleLowerCase().includes(query);
    const matchesLanguage = !language || section.languages.includes(language);
    return matchesSearch && matchesLanguage;
  });

  return (
    <div className="bg-muted/20 min-h-dvh p-6">
      {/* Header */}
      <div className="flex items-start justify-between mb-4 gap-4 flex-wrap">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <h2 className="text-2xl font-bold text-foreground">{t.templatesTitle}</h2>
            <span className="text-[10px] font-semibold uppercase tracking-wide px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-700 dark:text-amber-300 ring-1 ring-amber-500/20">
              Beta
            </span>
          </div>
          <p className="text-sm text-muted-foreground max-w-2xl">{t.templatesDesc}</p>
        </div>
        <button
          onClick={() => setShowBuilder(true)}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors shadow-sm"
        >
          <Plus size={14} />
          {t.templateBuilder}
          <ExternalLink size={12} className="opacity-70" />
        </button>
      </div>

      {/* Beta banner */}
      <div className="mb-5 px-4 py-3 rounded-lg bg-amber-500/5 ring-1 ring-amber-500/20 text-sm flex items-start gap-3">
        <Sparkles size={16} className="text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
        <div className="flex-1 text-amber-900 dark:text-amber-200">
          <span>Templates (beta) is powered by the </span>
          <span className="font-medium underline underline-offset-2">new templates and sections API</span>.
          <span className="ml-1">Please let us know what you'd like to see here or report any issues.</span>
        </div>
        <button
          type="button"
          onClick={() => navigate('/support')}
          className="text-xs px-3 py-1 rounded-md bg-amber-500/10 hover:bg-amber-500/20 text-amber-700 dark:text-amber-300 transition-colors"
        >
          Provide feedback
        </button>
      </div>

      {/* View toggle + filters */}
      <div className="flex items-center gap-3 mb-5 flex-wrap">
        {/* View radio group */}
        <div className="inline-flex items-center rounded-lg border border-border/20 bg-background p-0.5">
          {(['templates', 'sections'] as View[]).map(v => (
            <button
              key={v}
              onClick={() => setView(v)}
              className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
                view === v ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              {v === 'templates' ? t.viewTemplates : t.viewSections}
            </button>
          ))}
        </div>

        {view === 'sections' && (
          <button
            onClick={() => setShowSectionEditor(true)}
            className="inline-flex items-center gap-1.5 px-3 py-2 text-sm rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
          >
            <Plus size={13} /> New section
          </button>
        )}

        <div className="flex-1" />

        <div className="relative w-full max-w-xs">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none" />
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder={t.searchTemplatesPlaceholder}
            className="w-full pl-9 pr-3 py-2 text-sm rounded-lg border border-border/20 bg-background text-foreground placeholder:text-foreground/70 focus:outline-none focus:ring-1 focus:ring-ring"
          />
        </div>
        <select
          value={language}
          onChange={e => setLanguage(e.target.value as LanguageFilter)}
          className="appearance-none text-sm pl-3 pr-8 py-2 rounded-lg border border-border/20 bg-background text-foreground cursor-pointer hover:border-primary/30 focus:outline-none focus:ring-1 focus:ring-ring"
        >
          <option value="">{t.allTypes}</option>
          <option value="zh-CN">中文 (zh-CN)</option>
          <option value="en-US">English (en-US)</option>
        </select>
        <button
          className="inline-flex items-center gap-1 px-3 py-2 text-sm rounded-lg border border-border/20 bg-background text-foreground hover:bg-accent transition-colors"
        >
          {t.filter}
        </button>
      </div>

      {/* Sections catalog */}
      {view === 'sections' ? (
        sectionsLoading ? (
          <div className="flex items-center justify-center h-64">
            <Loader2 className="animate-spin h-8 w-8 text-muted-foreground" />
          </div>
        ) : sectionsError ? (
          <div className="bg-background rounded-xl p-8 text-center shadow-sm">
            <MessageSquareWarning size={28} className="mx-auto mb-3 text-destructive opacity-60" />
            <p className="text-sm text-destructive">{sectionsError}</p>
          </div>
        ) : visibleSections.length === 0 ? (
          <div className="bg-background rounded-xl shadow-sm p-12 text-center">
            <FileText size={32} className="mx-auto mb-3 text-muted-foreground opacity-40" />
            <p className="text-sm text-muted-foreground">No sections match the current filters.</p>
          </div>
        ) : (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
              {visibleSections.map(section => (
                <SectionCard
                  key={section.id}
                  section={section}
                  onEdit={() => setEditingSection(section)}
                  onDeleted={fetchSections}
                />
              ))}
            </div>
            <p className="text-xs text-muted-foreground mt-4 text-right">
              {visibleSections.length} / {sections.length}
            </p>
          </>
        )
      ) : (
        <>
          {/* Card grid */}
          {loading ? (
            <div className="flex items-center justify-center h-64">
              <Loader2 className="animate-spin h-8 w-8 text-muted-foreground" />
            </div>
          ) : error ? (
            <div className="bg-background rounded-xl p-8 text-center shadow-sm">
              <MessageSquareWarning size={28} className="mx-auto mb-3 text-destructive opacity-60" />
              <p className="text-sm text-destructive mb-4">{error}</p>
              <button onClick={fetchList} className="bg-primary text-primary-foreground rounded-lg px-4 py-2 text-sm font-medium hover:bg-primary/90 transition-colors">重试</button>
            </div>
          ) : items.length === 0 ? (
            <div className="bg-background rounded-xl p-12 text-center shadow-sm">
              <FileText size={32} className="mx-auto mb-3 text-muted-foreground opacity-40" />
              <p className="text-sm text-muted-foreground mb-4">{t.noTemplates}</p>
              <button
                onClick={() => setShowBuilder(true)}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors"
              >
                <Plus size={14} /> {t.templateBuilder}
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
              {items.map(tpl => (
                <TemplateCard
                  key={tpl.id}
                  template={tpl}
                  onDeleted={fetchList}
                  onEdit={() => setEditingTemplate(tpl)}
                />
              ))}
            </div>
          )}

          {/* Counter footer (no hard pagination in Beta) */}
          {!loading && !error && items.length > 0 && (
            <p className="text-xs text-muted-foreground mt-4 text-right">
              {items.length} / {total}
            </p>
          )}
        </>
      )}

      {showBuilder && (
        <TemplateBuilderModal
          availableSections={sections}
          onClose={() => setShowBuilder(false)}
          onSaved={() => { setShowBuilder(false); fetchList(); }}
        />
      )}
      {editingTemplate && (
        <TemplateBuilderModal
          initial={editingTemplate}
          availableSections={sections}
          onClose={() => setEditingTemplate(null)}
          onSaved={() => { setEditingTemplate(null); fetchList(); }}
        />
      )}
      {showSectionEditor && (
        <SectionEditorModal
          onClose={() => setShowSectionEditor(false)}
          onSaved={() => { setShowSectionEditor(false); fetchSections(); }}
        />
      )}
      {editingSection && (
        <SectionEditorModal
          initial={editingSection}
          onClose={() => setEditingSection(null)}
          onSaved={() => { setEditingSection(null); fetchSections(); }}
        />
      )}
    </div>
  );
}

function SectionCard({ section, onEdit, onDeleted }: { section: GuidedSection; onEdit: () => void; onDeleted: () => void; }) {
  const [busy, setBusy] = useState(false);
  const mutable = section.source !== 'corti' && Boolean(section.createdBy);

  async function handleDelete() {
    if (!confirm(`Delete section "${section.name}"? Existing saved templates keep their embedded definition.`)) return;
    setBusy(true);
    try {
      await templatesApi.deleteSection(section.id);
      onDeleted();
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="bg-background rounded-xl shadow-sm p-5 flex flex-col">
      <div className="flex items-start justify-between gap-2 mb-3">
        <div className="min-w-0">
          <h3 className="text-base font-semibold text-foreground truncate">{section.name}</h3>
          <p className="text-xs text-muted-foreground mt-1 line-clamp-3">
            {section.description || 'Reusable structured document section.'}
          </p>
        </div>
        {section.autoGenerated && (
          <Sparkles size={14} className="text-amber-500 shrink-0" aria-label="Auto-generated" />
        )}
      </div>
      <div className="flex items-center gap-2 mt-auto pt-2 flex-wrap">
        <span className="text-[10px] font-medium rounded px-1.5 py-0.5 bg-muted text-muted-foreground ring-1 ring-border">
          {section.source || 'project'}
        </span>
        {section.specialties.slice(0, 2).map(value => (
          <span key={value} className="text-[10px] rounded px-1.5 py-0.5 bg-primary/10 text-primary ring-1 ring-primary/20">
            {value}
          </span>
        ))}
        <span className="ml-auto text-[10px] text-muted-foreground">{section.languages.join(', ')}</span>
      </div>
      {mutable && (
        <div className="flex items-center justify-end gap-3 mt-3 pt-2 border-t border-border/10">
          <button onClick={onEdit} className="text-xs text-muted-foreground hover:text-foreground">Edit</button>
          <button
            onClick={handleDelete}
            disabled={busy}
            className="text-xs text-muted-foreground hover:text-destructive disabled:opacity-40"
          >
            {busy ? 'Deleting…' : 'Delete'}
          </button>
        </div>
      )}
    </div>
  );
}

function TemplateCard({ template, onDeleted, onEdit }: { template: Template; onDeleted: () => void; onEdit: () => void; }) {
  const t = useT();
  const [busy, setBusy] = useState(false);
  const categoryLabel = CATEGORY_LABEL_KEY[template.category]
    ? t[CATEGORY_LABEL_KEY[template.category] as keyof typeof t] as string
    : template.category;

  async function handleDelete() {
    if (!confirm(`Delete template "${template.name}"? This cannot be undone.`)) return;
    setBusy(true);
    try {
      await templatesApi.delete(template.id);
      onDeleted();
    } catch {
      // toast handled by interceptor
    } finally {
      setBusy(false);
    }
  }

  async function handlePublish() {
    setBusy(true);
    try {
      await templatesApi.publish(template.id);
      onDeleted();
    } catch {
      // toast handled by interceptor
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="group bg-background rounded-xl shadow-sm p-5 hover:ring-primary/30 transition-all flex flex-col">
      <div className="flex items-start justify-between gap-2 mb-3">
        <div className="flex-1 min-w-0">
          <h3 className="text-base font-semibold text-foreground truncate">{template.name}</h3>
          <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{template.description}</p>
        </div>
        <button
          onClick={template.is_builtin ? undefined : onEdit}
          disabled={template.is_builtin}
          title={template.is_builtin ? 'Built-in template is read-only' : 'Edit template'}
          className="p-1 rounded-md text-muted-foreground hover:bg-accent opacity-0 group-hover:opacity-100 transition-opacity disabled:cursor-not-allowed"
        >
          <MoreVertical size={14} />
        </button>
      </div>
      <div className="flex items-center gap-2 mt-auto pt-2 flex-wrap">
        {template.is_builtin && (
          <span className="inline-flex items-center text-[10px] font-semibold uppercase tracking-wider rounded px-1.5 py-0.5 bg-primary/10 text-primary ring-1 ring-primary/20">
            {t.builtinBadge}
          </span>
        )}
        <span className="inline-flex items-center text-[10px] font-medium rounded px-1.5 py-0.5 bg-muted text-muted-foreground ring-1 ring-border">
          {categoryLabel}
        </span>
        <span className="inline-flex items-center text-[10px] font-medium rounded px-1.5 py-0.5 bg-muted text-muted-foreground ring-1 ring-border">
          {t.scopeAllCustomers}
        </span>
        <span className={`inline-flex items-center text-[10px] font-medium rounded px-1.5 py-0.5 ring-1 ${
          template.published_version_count > 0
            ? 'bg-emerald-500/10 text-emerald-700 ring-emerald-500/20 dark:text-emerald-300'
            : 'bg-amber-500/10 text-amber-700 ring-amber-500/20 dark:text-amber-300'
        }`}>
          {template.published_version_count > 0
            ? `Published v${template.published_version?.version_number ?? 0}`
            : 'Draft'}
        </span>
        <span className="ml-auto inline-flex items-center text-[10px] text-muted-foreground">
          {template.language}
        </span>
      </div>
      {!template.is_builtin && (
        <div className="flex items-center justify-end gap-3 mt-2 pt-2 border-t border-border/10">
          <button
            onClick={handlePublish}
            disabled={busy}
            className="text-xs text-primary hover:text-primary/80 transition-colors disabled:opacity-40"
          >
            Publish
          </button>
          <button
            onClick={handleDelete}
            disabled={busy}
            className="text-xs text-muted-foreground hover:text-destructive transition-colors disabled:opacity-40"
          >
            {busy ? <Loader2 size={12} className="inline animate-spin mr-1" /> : null}
            Delete
          </button>
        </div>
      )}
    </div>
  );
}

function SectionEditorModal({ initial, onClose, onSaved }: { initial?: GuidedSection; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(initial?.name || '');
  const [description, setDescription] = useState(initial?.description || '');
  const [language, setLanguage] = useState<'zh-CN' | 'en-US'>((initial?.languages[0] as 'zh-CN' | 'en-US') || 'zh-CN');
  const [specialties, setSpecialties] = useState((initial?.specialties || ['custom']).join(', '));
  const initialType = String(initial?.generation?.outputSchema?.type || 'string');
  const [outputType, setOutputType] = useState<'string' | 'number' | 'boolean'>(
    ['string', 'number', 'boolean'].includes(initialType) ? initialType as 'string' | 'number' | 'boolean' : 'string',
  );
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  async function save() {
    if (!name.trim()) {
      setError('请填写章节名称');
      return;
    }
    setSaving(true);
    setError('');
    const payload = {
      name: name.trim(),
      description: description.trim(),
      language,
      specialties: specialties.split(',').map(value => value.trim()).filter(Boolean),
      outputSchema: { type: outputType },
    };
    try {
      if (initial) await templatesApi.updateSection(initial.id, payload);
      else await templatesApi.createSection(payload);
      onSaved();
    } catch (err: any) {
      const detail = err?.response?.data?.detail;
      setError(typeof detail === 'string' ? detail : detail?.reason || detail?.message || '保存章节失败');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-sm flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-background rounded-xl shadow-2xl w-full max-w-xl overflow-hidden" onClick={event => event.stopPropagation()}>
        <div className="px-5 py-4 border-b border-border/20 flex items-center justify-between">
          <h3 className="text-base font-semibold">{initial ? `Edit ${initial.name}` : 'New section'}</h3>
          <button onClick={onClose} className="p-1 rounded-md hover:bg-accent text-muted-foreground"><X size={16} /></button>
        </div>
        <div className="p-5 space-y-4">
          <div>
            <label className="block text-xs font-medium mb-1.5">Section name</label>
            <input value={name} onChange={event => setName(event.target.value)} autoFocus className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background focus:outline-none focus:ring-1 focus:ring-ring" />
          </div>
          <div>
            <label className="block text-xs font-medium mb-1.5">Generation instructions</label>
            <textarea value={description} onChange={event => setDescription(event.target.value)} rows={4} className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background focus:outline-none focus:ring-1 focus:ring-ring resize-y" />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-medium mb-1.5">Language</label>
              <select value={language} onChange={event => setLanguage(event.target.value as 'zh-CN' | 'en-US')} className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background">
                <option value="zh-CN">中文 (zh-CN)</option>
                <option value="en-US">English (en-US)</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-medium mb-1.5">Output type</label>
              <select value={outputType} onChange={event => setOutputType(event.target.value as 'string' | 'number' | 'boolean')} className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background">
                <option value="string">Text</option>
                <option value="number">Number</option>
                <option value="boolean">Boolean</option>
              </select>
            </div>
          </div>
          <div>
            <label className="block text-xs font-medium mb-1.5">Specialties (comma separated)</label>
            <input value={specialties} onChange={event => setSpecialties(event.target.value)} className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background" />
          </div>
          {error && <p className="text-xs text-destructive bg-destructive/10 rounded-lg px-3 py-2">{error}</p>}
        </div>
        <div className="px-5 py-3 border-t border-border/20 bg-muted/30 flex justify-end gap-2">
          <button onClick={onClose} className="px-4 py-2 text-sm rounded-lg border border-border/20 hover:bg-accent">取消</button>
          <button onClick={save} disabled={saving} className="px-4 py-2 text-sm rounded-lg bg-primary text-primary-foreground disabled:opacity-50">
            {saving ? 'Saving…' : 'Save section'}
          </button>
        </div>
      </div>
    </div>
  );
}

function parseTemplateDefinition(raw: string): { instructions: string; sectionIds: string[] } {
  try {
    const value = JSON.parse(raw);
    if (!value || typeof value !== 'object' || !Array.isArray(value.sections)) throw new Error('plain');
    return {
      instructions: typeof value.instructions?.prompt === 'string' ? value.instructions.prompt : '',
      sectionIds: value.sections.map((section: any) => section.sectionId).filter(Boolean),
    };
  } catch {
    return { instructions: raw, sectionIds: [] };
  }
}

function TemplateBuilderModal({ initial, availableSections, onClose, onSaved }: { initial?: Template; availableSections: GuidedSection[]; onClose: () => void; onSaved: () => void; }) {
  const t = useT();
  const parsedInitial = parseTemplateDefinition(initial?.content || '');
  const [name, setName] = useState(initial?.name || '');
  const [desc, setDesc] = useState(initial?.description || '');
  const [content, setContent] = useState(parsedInitial.instructions);
  const [category, setCategory] = useState(initial?.category || 'custom');
  const [language, setLanguage] = useState<'zh-CN' | 'en-US'>((initial?.language as 'zh-CN' | 'en-US') || 'zh-CN');
  const [sectionOptions, setSectionOptions] = useState<GuidedSection[]>(availableSections);
  const [selectedSectionIds, setSelectedSectionIds] = useState<string[]>(parsedInitial.sectionIds);
  const [submitting, setSubmitting] = useState(false);
  const [formError, setFormError] = useState('');
  const [sampleContext, setSampleContext] = useState('');
  const [previewing, setPreviewing] = useState(false);
  const [previewError, setPreviewError] = useState('');
  const [previewResult, setPreviewResult] = useState<{
    sections: Array<{ key: string; name: string; text: string; sort: number }>;
    creditsConsumed: number;
  } | null>(null);

  useEffect(() => {
    if (sectionOptions.length > 0) return;
    templatesApi.sections().then(response => setSectionOptions(response.data || [])).catch(() => setFormError('加载章节目录失败'));
  }, [sectionOptions.length]);

  async function runPreview() {
    const selectedSections = sectionOptions.filter(section => selectedSectionIds.includes(section.id));
    if (selectedSections.length === 0) {
      setPreviewError('Select at least one section before running a preview.');
      return;
    }
    if (!sampleContext.trim()) {
      setPreviewError('Add de-identified sample context before running a preview.');
      return;
    }
    setPreviewing(true);
    setPreviewError('');
    setPreviewResult(null);
    try {
      const response = await templatesApi.previewDocument(crypto.randomUUID(), {
        context: [{ type: 'string', data: sampleContext.trim() }],
        template: {
          sections: selectedSections.map(section => ({
            key: section.id,
            nameOverride: section.name,
            contentOverride: section.generation?.instructions?.contentPrompt || section.description || undefined,
            writingStyleOverride: section.generation?.instructions?.writingStylePrompt,
            additionalInstructionsOverride: section.generation?.instructions?.miscPrompt,
          })),
          description: desc.trim() || undefined,
          additionalInstructionsOverride: content.trim() || undefined,
        },
        name: name.trim() || 'Template preview',
        outputLanguage: language,
        documentationMode: 'global_sequential',
      });
      if (response.headers['x-corti-retention-policy'] !== 'acknowledged') {
        throw new Error('Preview retention policy was not acknowledged by the server.');
      }
      setPreviewResult({
        sections: [...response.data.sections].sort((a, b) => a.sort - b.sort),
        creditsConsumed: response.data.usageInfo.creditsConsumed,
      });
    } catch (err: any) {
      const detail = err?.response?.data?.detail;
      setPreviewError(
        typeof detail === 'string'
          ? detail
          : detail?.detail || detail?.message || err?.message || 'Preview generation failed.',
      );
    } finally {
      setPreviewing(false);
    }
  }

  async function submit() {
    if (!name.trim()) {
      setFormError('请填写模板名称');
      return;
    }
    const selectedSections = sectionOptions.filter(section => selectedSectionIds.includes(section.id));
    if (selectedSections.length === 0) {
      setFormError('请至少选择一个章节');
      return;
    }
    if (selectedSections.some(section => !section.languages.includes(language))) {
      setFormError(`所选章节必须支持模板语言 ${language}`);
      return;
    }
    setSubmitting(true);
    setFormError('');
    try {
      const definition = {
        instructions: {
          prompt: content.trim() || 'Generate only source-grounded content for each selected section.',
        },
        sections: selectedSections.map(section => ({
          ...(section.generation || {
            heading: section.name,
            instructions: {
              contentPrompt: section.description || 'Generate only source-grounded content.',
            },
            outputSchema: { type: 'string' },
          }),
          sectionId: section.id,
          sectionVersionId: section.versionId || section.generation?.sectionVersionId,
        })),
      };
      const payload = {
        name: name.trim(),
        description: desc.trim(),
        content: JSON.stringify(definition),
        category,
        language,
      };
      if (initial) await templatesApi.update(initial.id, payload);
      else await templatesApi.create(payload);
      onSaved();
    } catch (err: any) {
      const detail = err?.response?.data?.detail;
      setFormError(typeof detail === 'string' ? detail : detail?.message || '创建失败');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-sm flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-background rounded-xl shadow-2xl shadow-sm w-full max-w-5xl overflow-hidden" onClick={e => e.stopPropagation()}>
        <div className="px-5 py-4 border-b border-border/20 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-foreground">
              {initial ? `Edit ${initial.name}` : t.templateBuilder}
            </h3>
            <span className="text-[10px] font-semibold uppercase tracking-wide px-1.5 py-0.5 rounded bg-amber-500/10 text-amber-700 dark:text-amber-300 ring-1 ring-amber-500/20">Beta</span>
          </div>
          <button onClick={onClose} className="p-1 rounded-md hover:bg-accent text-muted-foreground">
            <X size={16} />
          </button>
        </div>
        <div className="p-5 space-y-4 max-h-[70vh] overflow-y-auto">
          <div>
            <label className="block text-xs font-medium text-foreground mb-1.5">Name</label>
            <input
              value={name}
              onChange={e => setName(e.target.value)}
              placeholder={t.templateNamePlaceholder}
              autoFocus
              className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background text-foreground focus:outline-none focus:ring-1 focus:ring-ring"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-foreground mb-1.5">Description</label>
            <input
              value={desc}
              onChange={e => setDesc(e.target.value)}
              placeholder={t.templateDescPlaceholder}
              className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background text-foreground focus:outline-none focus:ring-1 focus:ring-ring"
            />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-medium text-foreground mb-1.5">{t.templateCategory}</label>
              <select
                value={category}
                onChange={e => setCategory(e.target.value)}
                className="w-full appearance-none text-sm pl-3 pr-8 py-2 rounded-lg border border-border/20 bg-background text-foreground cursor-pointer focus:outline-none focus:ring-1 focus:ring-ring"
              >
                <option value="inpatient">{t.templateCategoryInpatient}</option>
                <option value="surgery">{t.templateCategorySurgery}</option>
                <option value="outpatient">{t.templateCategoryOutpatient}</option>
                <option value="emergency">{t.templateCategoryEmergency}</option>
                <option value="consultation">{t.templateCategoryConsultation}</option>
                <option value="custom">{t.templateCategoryCustom}</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-medium text-foreground mb-1.5">{t.templateLanguage}</label>
              <select
                value={language}
                onChange={e => setLanguage(e.target.value as 'zh-CN' | 'en-US')}
                className="w-full appearance-none text-sm pl-3 pr-8 py-2 rounded-lg border border-border/20 bg-background text-foreground cursor-pointer focus:outline-none focus:ring-1 focus:ring-ring"
              >
                <option value="zh-CN">{t.templateLanguageZh}</option>
                <option value="en-US">{t.templateLanguageEn}</option>
              </select>
            </div>
          </div>
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block text-xs font-medium text-foreground">Sections</label>
              <span className="text-[10px] text-muted-foreground">{selectedSectionIds.length} selected</span>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2 max-h-48 overflow-y-auto rounded-lg border border-border/20 p-2">
              {sectionOptions
                .filter(section => section.languages.includes(language))
                .map(section => {
                  const checked = selectedSectionIds.includes(section.id);
                  return (
                    <label key={section.id} className={`flex items-start gap-2 rounded-md p-2 cursor-pointer ${checked ? 'bg-primary/10 ring-1 ring-primary/20' : 'hover:bg-accent'}`}>
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={() => setSelectedSectionIds(current => (
                          checked ? current.filter(id => id !== section.id) : [...current, section.id]
                        ))}
                        className="mt-0.5"
                      />
                      <span className="min-w-0">
                        <span className="block text-xs font-medium truncate">{section.name}</span>
                        <span className="block text-[10px] text-muted-foreground line-clamp-2">{section.description}</span>
                      </span>
                    </label>
                  );
                })}
              {sectionOptions.filter(section => section.languages.includes(language)).length === 0 && (
                <p className="col-span-full text-xs text-muted-foreground p-3 text-center">
                  No sections support {language}. Create a section in the Sections view first.
                </p>
              )}
            </div>
          </div>
          <div>
            <label className="block text-xs font-medium text-foreground mb-1.5">Template instructions</label>
            <textarea
              value={content}
              onChange={e => setContent(e.target.value)}
              placeholder={t.templateContentPlaceholder}
              rows={4}
              className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background text-foreground focus:outline-none focus:ring-1 focus:ring-ring resize-y font-mono"
            />
          </div>
          <div className="rounded-lg border border-border/20 bg-muted/20 p-4">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-semibold">Structure preview</span>
              <span className="text-[10px] text-muted-foreground">No LLM call</span>
            </div>
            {selectedSectionIds.length === 0 ? (
              <p className="text-xs text-muted-foreground">Select sections to preview the generated document structure.</p>
            ) : (
              <div className="space-y-3">
                {sectionOptions.filter(section => selectedSectionIds.includes(section.id)).map((section, index) => (
                  <div key={section.id} className="rounded-md bg-background p-3 ring-1 ring-border/20">
                    <p className="text-xs font-semibold">{index + 1}. {section.name}</p>
                    <p className="text-[11px] text-muted-foreground mt-1">{section.description || 'Source-grounded section content.'}</p>
                    <p className="text-[10px] text-muted-foreground mt-1">Output: {String(section.generation?.outputSchema?.type || 'string')}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
          <div className="rounded-lg border border-border/20 bg-muted/20 p-4 space-y-3">
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold">Run with sample context</p>
                <p className="text-[10px] text-muted-foreground mt-0.5">
                  Zero-retention generation with grounding Guardrails. Human review is required.
                </p>
              </div>
              <button
                type="button"
                onClick={runPreview}
                disabled={previewing || selectedSectionIds.length === 0 || !sampleContext.trim()}
                className="inline-flex shrink-0 items-center gap-2 px-3 py-1.5 text-xs rounded-md bg-primary text-primary-foreground font-medium hover:bg-primary/90 disabled:opacity-50"
              >
                {previewing ? <Loader2 size={12} className="animate-spin" /> : <Sparkles size={12} />}
                Run preview
              </button>
            </div>
            <textarea
              value={sampleContext}
              onChange={event => {
                setSampleContext(event.target.value);
                setPreviewResult(null);
                setPreviewError('');
              }}
              placeholder="Use de-identified clinical sample text only."
              rows={4}
              className="w-full px-3 py-2 text-sm rounded-lg border border-border/20 bg-background text-foreground focus:outline-none focus:ring-1 focus:ring-ring resize-y"
            />
            {previewError && (
              <p className="text-xs text-destructive bg-destructive/10 rounded-md px-3 py-2">{previewError}</p>
            )}
            {previewResult && (
              <div className="space-y-2">
                <div className="flex items-center justify-between text-[10px] text-muted-foreground">
                  <span>X-Corti-Retention-Policy: acknowledged</span>
                  <span>Credits: {previewResult.creditsConsumed.toFixed(6)}</span>
                </div>
                {previewResult.sections.map(section => (
                  <div key={section.key} className="rounded-md bg-background p-3 ring-1 ring-border/20">
                    <p className="text-xs font-semibold">{section.name}</p>
                    <p className="text-xs text-foreground whitespace-pre-wrap mt-1">
                      {section.text || <span className="text-muted-foreground">No supported content generated.</span>}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </div>
          {formError && (
            <p className="text-xs text-destructive bg-destructive/10 rounded-lg px-3 py-2">{formError}</p>
          )}
        </div>
        <div className="px-5 py-3 border-t border-border/20 bg-muted/30 flex items-center justify-end gap-2">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm rounded-lg border border-border/20 text-foreground hover:bg-accent transition-colors"
          >
            取消
          </button>
          <button
            onClick={submit}
            disabled={submitting || selectedSectionIds.length === 0}
            className="inline-flex items-center gap-2 px-4 py-2 text-sm rounded-lg bg-primary text-primary-foreground font-medium hover:bg-primary/90 transition-colors disabled:opacity-50"
          >
            {submitting && <Loader2 size={12} className="animate-spin" />}
            {initial ? 'Save changes' : t.createTemplate}
          </button>
        </div>
      </div>
    </div>
  );
}
