"""iCoDer ``GET /api/v2/tools/templates/`` + ``/sections/`` — Corti §13.4 LIST.

Cycle 4 (2026-07-01) — wire-shape parity for the read-only discovery path
that an SDK caller needs in order to find templates and sections to pass
to the cycle-3 generator endpoint.

Spec sources (ground truth, never inferred):
- ``docs/corti-reverse-engineered/guided-templates-list.md`` — operationId
  ``guided_templates_list``, path ``GET /documents/templates/``.
- ``docs/corti-reverse-engineered/guided-sections-list.md`` — operationId
  ``guided_sections_list``, path ``GET /documents/sections/``.

What this endpoint IS
---------------------
- A read-only LIST endpoint returning Corti-shape template/section metadata
  from tenant templates, curated sections, and persisted dynamic sections.

What this endpoint is NOT
--------------------------
- NOT the full Corti CRUD/publish/version surface. Template rows come from
  iCoDer's tenant database; sections combine a versioned product catalog with
  tenant-scoped resources created by Guided Document generation.
- NOT a replacement for the legacy M3-0 ``/api/templates`` surface.
  That DB-backed CRUD with iCoDer-Chinese category enums stays untouched
  in this cycle; cleaning it up is a separate Phase 2 task.

Filter handling
---------------
The spec accepts repeatable ``lang``, ``region``, ``specialty``, ``label``
query params, a ``published`` boolean, and a ``source`` enum. Cycle 4
accepts the params and applies a simple subset match (template is
included if **every** provided filter matches its projected metadata — empty
filter list ⇒ all entries returned). This is enough to exercise the
filter contract without overcommitting to a filter algorithm the real
DB layer will replace in a later cycle.
"""

from __future__ import annotations

from typing import Any, List, Literal, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Response
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.middleware.auth import get_current_organization, get_current_user
from app.models.organization import Organization
from app.models.template import Template, TemplateVersion
from app.models.user import User
from app.services.guided_template_catalog import (
    public_template_id,
    public_template_version_id,
    resolve_public_template,
    template_definition,
    template_generation,
)
from app.services.guided_section_catalog import resolve_curated_section
from app.services.guided_section_repository import guided_section_repository
from app.schemas.v2_tools_sections_templates import (
    GuidedLabel,
    GuidedSection,
    GuidedSectionCreate,
    GuidedSectionUpdate,
    GuidedTemplate,
    GuidedTemplateVersion,
)
from app.middleware.audit import log_action
from app.api.templates import publish_template

router = APIRouter(prefix="/api/v2/tools", tags=["v2-tools"])


# ─── Built-in section catalog ───────────────────────────────────────


def _now_iso() -> str:
    """ISO 8601 UTC timestamp (deterministic per-test override)."""
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


_CURATED_SECTIONS: List[GuidedSection] = [
    GuidedSection(
        id="44444444-aaaa-bbbb-cccc-444444444444",
        inheritedFromId=None,
        autoGenerated=False,
        source="corti",
        name="Subjective",
        languages=["en-US", "en-GB"],
        regions=["USA", "GBR"],
        specialties=["internal-medicine"],
        description="Patient-reported symptoms and history (SOAP).",
        labels=[GuidedLabel(key="section_role", value="subjective")],
        createdBy=None,
        createdAt="2026-01-15T08:00:00Z",
        updatedAt="2026-06-01T12:00:00Z",
        deletedAt=None,
    ),
    GuidedSection(
        id="55555555-aaaa-bbbb-cccc-555555555555",
        inheritedFromId=None,
        autoGenerated=False,
        source="corti",
        name="Plan",
        languages=["en-US"],
        regions=["USA"],
        specialties=["cardiology"],
        description="Treatment plan and follow-up steps.",
        labels=[GuidedLabel(key="section_role", value="plan")],
        createdBy=None,
        createdAt="2026-03-22T09:30:00Z",
        updatedAt="2026-05-15T16:45:00Z",
        deletedAt=None,
    ),
]

_CHINA_CURATED_SECTIONS = [
    ("10000001-aaaa-4c01-8c01-100000000001", "主诉", "主要症状或体征及持续时间。", "chief-complaint"),
    ("10000002-aaaa-4c02-8c02-100000000002", "现病史", "按时间顺序记录本次疾病的发生、演变和诊疗经过。", "history-present-illness"),
    ("10000003-aaaa-4c03-8c03-100000000003", "既往史", "既往健康、疾病、手术外伤、输血等已记录情况。", "past-medical-history"),
    ("10000004-aaaa-4c04-8c04-100000000004", "过敏史", "药物、食物或其他过敏及已记录反应。", "allergies"),
    ("10000005-aaaa-4c05-8c05-100000000005", "体格检查", "生命体征、阳性体征、必要阴性体征和专科检查。", "physical-examination"),
    ("10000006-aaaa-4c06-8c06-100000000006", "辅助检查", "与本次诊疗相关的检验、影像和其他检查结果。", "diagnostic-results"),
    ("10000007-aaaa-4c07-8c07-100000000007", "诊断与评估", "已记录的诊断、待查问题和鉴别诊断。", "assessment"),
    ("10000008-aaaa-4c08-8c08-100000000008", "诊疗计划", "已记录的检查、治疗、用药、随访和安全提示。", "plan"),
    ("10000009-aaaa-4c09-8c09-100000000009", "出院情况与医嘱", "已记录的出院情况、诊断、用药、复诊和注意事项。", "discharge"),
]

_CURATED_SECTIONS.extend(
    GuidedSection(
        id=section_id,
        inheritedFromId=None,
        autoGenerated=False,
        source="project",
        name=name,
        languages=["zh-CN"],
        regions=["CHN"],
        specialties=["general-medicine"],
        description=description,
        labels=[
            GuidedLabel(key="section_role", value=role),
            GuidedLabel(key="regulatory_basis", value="CN-medical-record-standard"),
        ],
        createdBy=None,
        createdAt="2026-08-14T00:00:00Z",
        updatedAt="2026-08-14T00:00:00Z",
        deletedAt=None,
    )
    for section_id, name, description, role in _CHINA_CURATED_SECTIONS
)


def _template_projection(
    row: Template,
    version: TemplateVersion | None = None,
) -> GuidedTemplate:
    """Project a tenant Template row to Corti's discovery shape."""
    language = row.language.value if hasattr(row.language, "value") else str(row.language)
    category = row.category.value if hasattr(row.category, "value") else str(row.category)
    created_at = row.created_at or row.updated_at
    updated_at = row.updated_at or created_at
    definition = template_definition(row)
    inherited_from_id = (
        definition.get("inheritedFromId") if definition else None
    )
    auto_generated = bool(
        definition and ("sections" in definition or inherited_from_id)
    )
    published_version = None
    if version is not None:
        import json
        published_version = GuidedTemplateVersion(
            id=version.id,
            versionNumber=version.version_number,
            generation=json.loads(version.generation_json),
            deletedAt=None,
        )
    elif row.is_builtin:
        published_version = GuidedTemplateVersion(
            id=public_template_version_id(row),
            versionNumber=0,
            generation=template_generation(row),
            deletedAt=None,
        )
    return GuidedTemplate(
        id=public_template_id(row),
        inheritedFromId=inherited_from_id,
        autoGenerated=auto_generated,
        source="corti" if row.is_builtin else "user",
        name=row.name,
        description=row.description or "",
        languages=[language],
        regions=["CHN" if language == "zh-CN" else "USA"],
        specialties=[category],
        labels=[GuidedLabel(key="category", value=category)],
        publishedVersion=published_version,
        createdBy=None,
        createdAt=(created_at.isoformat() if created_at else _now_iso()),
        updatedAt=(updated_at.isoformat() if updated_at else _now_iso()),
        deletedAt=None,
    )


def _stored_section_projection(row) -> GuidedSection:
    definition = guided_section_repository.definition(row)
    instructions = definition.get("instructions", {})
    description = instructions.get("contentPrompt") if isinstance(instructions, dict) else None
    raw_labels = definition.get("labels", [])
    labels = [GuidedLabel(**item) for item in raw_labels if isinstance(item, dict)]
    return GuidedSection(
        id=row.section_id,
        inheritedFromId=definition.get("inheritedFromId"),
        autoGenerated=row.auto_generated,
        versionId=row.version_id,
        generation=definition,
        source=row.source if row.source in {"user", "corti", "project"} else "project",
        name=row.name,
        languages=[row.language],
        regions=["CHN" if row.language.casefold().startswith("zh") else "USA"],
        specialties=definition.get("specialties", ["custom"]),
        description=description,
        labels=labels or [GuidedLabel(key="resource_type", value="dynamic-section")],
        createdBy=row.owner_id,
        createdAt=row.created_at.isoformat(),
        updatedAt=row.updated_at.isoformat(),
        deletedAt=row.deleted_at.isoformat() if row.deleted_at else None,
    )


def _curated_section_projection(section: GuidedSection) -> GuidedSection:
    definition = resolve_curated_section(section.id)
    return section.model_copy(update={
        "versionId": definition.get("sectionVersionId") if definition else None,
        "generation": definition,
    })


def _validate_section_output_schema(node: Any, path: str = "outputSchema") -> None:
    if not isinstance(node, dict):
        raise ValueError(f"{path} must be an object")
    node_type = node.get("type")
    if node_type not in {"string", "number", "boolean", "array", "object"}:
        raise ValueError(f"{path}.type is unsupported")
    if node_type == "array":
        if "items" not in node:
            raise ValueError(f"{path}.items is required")
        _validate_section_output_schema(node["items"], f"{path}.items")
    if node_type == "object":
        seen: set[str] = set()
        for index, field in enumerate(node.get("fields", [])):
            key = str(field.get("key", "")).strip() if isinstance(field, dict) else ""
            if not key:
                raise ValueError(f"{path}.fields[{index}].key is required")
            if key in seen:
                raise ValueError(f"{path}.fields contains duplicate key {key}")
            seen.add(key)
            _validate_section_output_schema(field.get("value"), f"{path}.fields[{index}].value")


def _section_definition(
    *,
    name: str,
    description: str,
    specialties: list[str],
    labels: list[GuidedLabel],
    output_schema: dict[str, Any],
) -> dict[str, Any]:
    _validate_section_output_schema(output_schema)
    return {
        "heading": name,
        "instructions": {
            "contentPrompt": description or "Generate only content supported by the source context."
        },
        "outputSchema": output_schema,
        "specialties": specialties or ["custom"],
        "labels": [item.model_dump(mode="json") for item in labels],
    }


def _can_manage_section(row, current_user: User) -> bool:
    role = getattr(getattr(current_user, "role", None), "value", getattr(current_user, "role", None))
    return row.owner_id == str(current_user.id) or role == "admin"


# ─── Filter helpers ─────────────────────────────────────────────────


def _apply_filters(
    items: List[dict],
    *,
    lang: List[str],
    region: List[str],
    specialty: List[str],
    label: List[str],
    published: Optional[bool],
    source: Optional[Literal["user", "corti", "project"]],
) -> List[dict]:
    """Subset filter — every provided filter must match (AND across categories,
    OR within a category).

    Empty filter list ⇒ all items pass. Soft-deleted items are excluded
    unless the caller opts in via a future ``includeDeleted`` flag
    (intentionally NOT supported in Cycle 4 — ``published=false`` is the
    only "non-published" notion surfaced by the spec, not "deleted").
    """
    out: List[dict] = []
    for it in items:
        d = it.model_dump(mode="json") if hasattr(it, "model_dump") else dict(it)
        # Soft-delete exclusion
        if d.get("deletedAt"):
            continue
        if lang and not (set(lang) & set(d.get("languages", []))):
            continue
        if region and not (set(region) & set(d.get("regions", []))):
            continue
        if specialty and not (set(specialty) & set(d.get("specialties", []))):
            continue
        if label:
            kv_set = {f"{lab['key']}:{lab['value']}" for lab in d.get("labels", [])}
            if not (set(label) & kv_set):
                continue
        if source is not None and d.get("source") != source:
            continue
        # The current catalog has no publishedVersion; treat all entries as
        # implicitly "published=true" (existence implies a version).
        # published=false ⇒ empty result (no unpublished rows exposed yet).
        is_published = d.get("publishedVersion") is not None
        if published is not None and is_published is not published:
            continue
        out.append(d)
    return out


# ─── Endpoints ──────────────────────────────────────────────────────


@router.get(
    "/templates/",
    response_model=List[GuidedTemplate],
    response_model_exclude_none=True,
    status_code=200,
)
@router.get(
    "/templates",
    response_model=List[GuidedTemplate],
    response_model_exclude_none=True,
    status_code=200,
)
async def list_v2_tools_templates(
    lang: List[str] = Query(default_factory=list, description="BCP 47 language tag filter; repeatable"),
    region: List[str] = Query(default_factory=list, description="ISO 3166-1 alpha-3 region code filter; repeatable"),
    specialty: List[str] = Query(default_factory=list, description="Clinical specialty filter; repeatable"),
    label: List[str] = Query(default_factory=list, description="Filter as `key:value`; repeatable"),
    published: Optional[bool] = Query(default=None, description="true=published only, false=unpublished only, omit=both"),
    source: Optional[Literal["user", "corti", "project"]] = Query(default=None, description="Content source filter"),
    current_user: User = Depends(get_current_user),
    current_org: Organization = Depends(get_current_organization),
    db: AsyncSession = Depends(get_db),
) -> List[GuidedTemplate]:
    """List authenticated tenant templates in Corti's discovery shape."""
    rows = list((await db.scalars(
        select(Template).where(
            Template.organization_id == current_org.id,
            Template.deleted_at.is_(None),
        )
        .order_by(Template.is_builtin.desc(), Template.created_at.desc())
    )).all())
    latest_versions: dict[str, TemplateVersion] = {}
    if rows:
        versions = list((await db.scalars(
            select(TemplateVersion).where(
                TemplateVersion.organization_id == current_org.id,
                TemplateVersion.template_id.in_([row.id for row in rows]),
            ).order_by(TemplateVersion.version_number.desc())
        )).all())
        for version in versions:
            latest_versions.setdefault(version.template_id, version)
    templates = [
        _template_projection(row, latest_versions.get(row.id)) for row in rows
    ]
    return [GuidedTemplate(**d) for d in _apply_filters(
        templates, lang=lang, region=region, specialty=specialty,
        label=label, published=published, source=source,
    )]


@router.get(
    "/templates/{template_id}",
    response_model=GuidedTemplate,
    response_model_exclude_none=True,
    status_code=200,
)
async def get_v2_tools_template(
    template_id: str,
    current_user: User = Depends(get_current_user),
    current_org: Organization = Depends(get_current_organization),
    db: AsyncSession = Depends(get_db),
) -> GuidedTemplate:
    """Get one opaque public template within the authenticated tenant."""
    row = await resolve_public_template(
        db,
        organization_id=str(current_org.id),
        template_id=template_id,
    )
    if row is None:
        raise HTTPException(
            status_code=404,
            detail={"error": "template_not_found", "templateId": template_id},
        )
    version = (await db.scalars(
        select(TemplateVersion).where(
            TemplateVersion.organization_id == current_org.id,
            TemplateVersion.template_id == row.id,
        ).order_by(TemplateVersion.version_number.desc()).limit(1)
    )).first()
    return _template_projection(row, version)


@router.post(
    "/templates/{template_id}/publish",
    response_model=GuidedTemplateVersion,
    status_code=201,
)
async def publish_v2_tools_template(
    template_id: str,
    current_user: User = Depends(get_current_user),
    current_org: Organization = Depends(get_current_organization),
    db: AsyncSession = Depends(get_db),
) -> GuidedTemplateVersion:
    """iCoDer extension: publish a public-ID template as an immutable version."""
    row = await resolve_public_template(
        db,
        organization_id=str(current_org.id),
        template_id=template_id,
    )
    if row is None:
        raise HTTPException(
            status_code=404,
            detail={"error": "template_not_found", "templateId": template_id},
        )
    published = await publish_template(
        template_id=row.id,
        user=current_user,
        current_org=current_org,
        db=db,
    )
    return GuidedTemplateVersion(
        id=published.id,
        versionNumber=published.version_number,
        generation=published.generation,
        deletedAt=None,
    )


@router.get(
    "/sections/",
    response_model=List[GuidedSection],
    status_code=200,
)
@router.get(
    "/sections",
    response_model=List[GuidedSection],
    status_code=200,
)
async def list_v2_tools_sections(
    lang: List[str] = Query(default_factory=list, description="BCP 47 language tag filter; repeatable"),
    region: List[str] = Query(default_factory=list, description="ISO 3166-1 alpha-3 region code filter; repeatable"),
    specialty: List[str] = Query(default_factory=list, description="Clinical specialty filter; repeatable"),
    label: List[str] = Query(default_factory=list, description="Filter as `key:value`; repeatable"),
    published: Optional[bool] = Query(default=None, description="true=published only, false=unpublished only, omit=both"),
    source: Optional[Literal["user", "corti", "project"]] = Query(default=None, description="Content source filter"),
    current_user: User = Depends(get_current_user),
    current_org: Organization = Depends(get_current_organization),
    db: AsyncSession = Depends(get_db),
) -> List[GuidedSection]:
    """List the versioned built-in section catalog; no LLM is required."""
    stored = await guided_section_repository.list(
        db, organization_id=str(current_org.id)
    )
    sections = [
        *[_curated_section_projection(section) for section in _CURATED_SECTIONS],
        *[_stored_section_projection(row) for row in stored],
    ]
    return [GuidedSection(**d) for d in _apply_filters(
        sections, lang=lang, region=region, specialty=specialty,
        label=label, published=published, source=source,
    )]


@router.post(
    "/sections/",
    response_model=GuidedSection,
    status_code=201,
)
@router.post(
    "/sections",
    response_model=GuidedSection,
    status_code=201,
)
async def create_v2_tools_section(
    body: GuidedSectionCreate,
    current_user: User = Depends(get_current_user),
    current_org: Organization = Depends(get_current_organization),
    db: AsyncSession = Depends(get_db),
) -> GuidedSection:
    """Create an encrypted tenant-owned section for the local Builder."""
    try:
        definition = _section_definition(
            name=body.name,
            description=body.description,
            specialties=body.specialties,
            labels=body.labels,
            output_schema=body.outputSchema,
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=422,
            detail={"error": "invalid_output_schema", "reason": str(exc)},
        ) from exc
    row = await guided_section_repository.create(
        db,
        organization_id=str(current_org.id),
        owner_id=str(current_user.id),
        language=body.language,
        definition=definition,
        auto_generated=False,
        source="user",
    )
    await log_action(
        db,
        str(current_user.id),
        current_user.username,
        "guided_section.create",
        "guided_section",
        row.section_id,
        organization_id=str(current_org.id),
    )
    await db.commit()
    await db.refresh(row)
    return _stored_section_projection(row)


@router.get(
    "/sections/{section_id}",
    response_model=GuidedSection,
    status_code=200,
)
async def get_v2_tools_section(
    section_id: str,
    current_user: User = Depends(get_current_user),
    current_org: Organization = Depends(get_current_organization),
    db: AsyncSession = Depends(get_db),
) -> GuidedSection:
    """Get one curated or tenant-created section without invoking an LLM."""
    curated = next((section for section in _CURATED_SECTIONS if section.id == section_id), None)
    if curated is not None:
        return _curated_section_projection(curated)
    stored = await guided_section_repository.list(
        db, organization_id=str(current_org.id)
    )
    row = next((item for item in stored if item.section_id == section_id), None)
    if row is None:
        raise HTTPException(
            status_code=404,
            detail={"error": "section_not_found", "sectionId": section_id},
        )
    return _stored_section_projection(row)


@router.patch(
    "/sections/{section_id}",
    response_model=GuidedSection,
    status_code=200,
)
async def update_v2_tools_section(
    section_id: str,
    body: GuidedSectionUpdate,
    current_user: User = Depends(get_current_user),
    current_org: Organization = Depends(get_current_organization),
    db: AsyncSession = Depends(get_db),
) -> GuidedSection:
    if any(section.id == section_id for section in _CURATED_SECTIONS):
        raise HTTPException(
            status_code=403,
            detail={"error": "section_builtin_protected", "sectionId": section_id},
        )
    row = await guided_section_repository.get(
        db, organization_id=str(current_org.id), section_id=section_id
    )
    if row is None:
        raise HTTPException(
            status_code=404,
            detail={"error": "section_not_found", "sectionId": section_id},
        )
    if not _can_manage_section(row, current_user):
        raise HTTPException(status_code=403, detail={"error": "section_forbidden"})
    current = guided_section_repository.definition(row)
    changes = body.model_dump(exclude_unset=True)
    instructions = current.get("instructions", {})
    current_description = (
        instructions.get("contentPrompt", "") if isinstance(instructions, dict) else ""
    )
    try:
        definition = _section_definition(
            name=changes.get("name", row.name),
            description=changes.get("description", current_description),
            specialties=changes.get("specialties", current.get("specialties", ["custom"])),
            labels=[
                item if isinstance(item, GuidedLabel) else GuidedLabel(**item)
                for item in changes.get("labels", current.get("labels", []))
            ],
            output_schema=changes.get("outputSchema", current.get("outputSchema", {"type": "string"})),
        )
    except (ValueError, TypeError) as exc:
        raise HTTPException(
            status_code=422,
            detail={"error": "invalid_section", "reason": str(exc)},
        ) from exc
    await guided_section_repository.update(
        db,
        row,
        language=changes.get("language", row.language),
        definition=definition,
    )
    await log_action(
        db,
        str(current_user.id),
        current_user.username,
        "guided_section.update",
        "guided_section",
        row.section_id,
        organization_id=str(current_org.id),
    )
    await db.commit()
    await db.refresh(row)
    return _stored_section_projection(row)


@router.delete(
    "/sections/{section_id}",
    status_code=204,
)
async def delete_v2_tools_section(
    section_id: str,
    current_user: User = Depends(get_current_user),
    current_org: Organization = Depends(get_current_organization),
    db: AsyncSession = Depends(get_db),
) -> Response:
    if any(section.id == section_id for section in _CURATED_SECTIONS):
        raise HTTPException(
            status_code=403,
            detail={"error": "section_builtin_protected", "sectionId": section_id},
        )
    row = await guided_section_repository.get(
        db, organization_id=str(current_org.id), section_id=section_id
    )
    if row is None:
        raise HTTPException(
            status_code=404,
            detail={"error": "section_not_found", "sectionId": section_id},
        )
    if not _can_manage_section(row, current_user):
        raise HTTPException(status_code=403, detail={"error": "section_forbidden"})
    await guided_section_repository.soft_delete(db, row)
    await log_action(
        db,
        str(current_user.id),
        current_user.username,
        "guided_section.delete",
        "guided_section",
        row.section_id,
        organization_id=str(current_org.id),
    )
    await db.commit()
    return Response(status_code=204)
