"""iCoDer ``GET /api/v2/tools/templates/`` + ``/sections/`` — Corti §13.4 LIST.

Cycle 4 (2026-07-01) — wire-shape parity for the read-only discovery path
that an SDK caller needs in order to find templates and sections to pass
to the cycle-3 generator endpoint.

Spec sources (ground truth, never inferred):
- ``docs/corti-reverse-engineered/guided-templates-list.md`` — operationId
  ``guided_templates_list``, path ``GET /documents/templates/``.
- ``docs/corti-reverse-engineered/guided-sections-list.md`` — operationId
  ``guided_sections_list``, path ``GET /documents/sections/``.

What this endpoint IS
---------------------
- A read-only LIST endpoint returning the Corti-shape template/section
  metadata envelope.

What this endpoint is NOT
--------------------------
- NOT a real CRUD surface. Cycle 4 ships stub data (one Corti-standard
  template + one user-created template; one Corti-standard section + one
  user-created section) to validate the wire contract. Full CRUD
  (create / update / delete / publish / version) lands in follow-on
  cycles once real storage is designed.
- NOT a replacement for the legacy M3-0 ``/api/templates`` surface.
  That DB-backed CRUD with iCoDer-Chinese category enums stays untouched
  in this cycle; cleaning it up is a separate Phase 2 task.

Filter handling
---------------
The spec accepts repeatable ``lang``, ``region``, ``specialty``, ``label``
query params, a ``published`` boolean, and a ``source`` enum. Cycle 4
accepts the params and applies a simple subset match (template is
included if **every** provided filter matches its stub data — empty
filter list ⇒ all entries returned). This is enough to exercise the
filter contract without overcommitting to a filter algorithm the real
DB layer will replace in a later cycle.
"""

from __future__ import annotations

import os
import uuid
from typing import List, Literal, Optional

from fastapi import APIRouter, Depends, HTTPException, Query

from app.middleware.auth import get_current_user
from app.models.user import User
from app.schemas.v2_tools_sections_templates import (
    GuidedLabel,
    GuidedSection,
    GuidedTemplate,
)

router = APIRouter(prefix="/api/v2/tools", tags=["v2-tools"])


# ─── Stub data (Cycle 4; replaced by real storage in a later cycle) ──


def _now_iso() -> str:
    """ISO 8601 UTC timestamp (deterministic per-test override)."""
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


_STUB_TEMPLATES: List[GuidedTemplate] = [
    GuidedTemplate(
        id="11111111-aaaa-bbbb-cccc-111111111111",
        inheritedFromId=None,
        autoGenerated=False,
        source="corti",
        name="Corti Standard — Discharge Summary",
        description="Standard Corti-curated discharge summary template.",
        languages=["en-US", "en-GB"],
        regions=["USA", "GBR"],
        specialties=["internal-medicine"],
        labels=[GuidedLabel(key="encounter_type", value="inpatient")],
        createdBy=None,
        createdAt="2026-01-15T08:00:00Z",
        updatedAt="2026-06-01T12:00:00Z",
        deletedAt=None,
    ),
    GuidedTemplate(
        id="22222222-aaaa-bbbb-cccc-222222222222",
        inheritedFromId=None,
        autoGenerated=False,
        source="user",
        name="Custom — Cardiology Outpatient Note",
        description="User-authored cardiology outpatient template.",
        languages=["en-US"],
        regions=["USA"],
        specialties=["cardiology"],
        labels=[GuidedLabel(key="encounter_type", value="outpatient")],
        createdBy="33333333-3333-3333-3333-333333333333",
        createdAt="2026-03-22T09:30:00Z",
        updatedAt="2026-05-15T16:45:00Z",
        deletedAt=None,
    ),
]


_STUB_SECTIONS: List[GuidedSection] = [
    GuidedSection(
        id="44444444-aaaa-bbbb-cccc-444444444444",
        inheritedFromId=None,
        autoGenerated=False,
        source="corti",
        name="Subjective",
        languages=["en-US", "en-GB"],
        regions=["USA", "GBR"],
        specialties=["internal-medicine"],
        description="Patient-reported symptoms and history (SOAP).",
        labels=[GuidedLabel(key="section_role", value="subjective")],
        createdBy=None,
        createdAt="2026-01-15T08:00:00Z",
        updatedAt="2026-06-01T12:00:00Z",
        deletedAt=None,
    ),
    GuidedSection(
        id="55555555-aaaa-bbbb-cccc-555555555555",
        inheritedFromId=None,
        autoGenerated=False,
        source="user",
        name="Plan",
        languages=["en-US"],
        regions=["USA"],
        specialties=["cardiology"],
        description="Treatment plan and follow-up steps.",
        labels=[GuidedLabel(key="section_role", value="plan")],
        createdBy="33333333-3333-3333-3333-333333333333",
        createdAt="2026-03-22T09:30:00Z",
        updatedAt="2026-05-15T16:45:00Z",
        deletedAt=None,
    ),
]


# ─── Filter helpers ─────────────────────────────────────────────────


def _apply_filters(
    items: List[dict],
    *,
    lang: List[str],
    region: List[str],
    specialty: List[str],
    label: List[str],
    published: Optional[bool],
    source: Optional[Literal["user", "corti"]],
) -> List[dict]:
    """Subset filter — every provided filter must match (AND across categories,
    OR within a category).

    Empty filter list ⇒ all items pass. Soft-deleted items are excluded
    unless the caller opts in via a future ``includeDeleted`` flag
    (intentionally NOT supported in Cycle 4 — ``published=false`` is the
    only "non-published" notion surfaced by the spec, not "deleted").
    """
    out: List[dict] = []
    for it in items:
        d = it.model_dump(mode="json") if hasattr(it, "model_dump") else dict(it)
        # Soft-delete exclusion
        if d.get("deletedAt"):
            continue
        if lang and not (set(lang) & set(d.get("languages", []))):
            continue
        if region and not (set(region) & set(d.get("regions", []))):
            continue
        if specialty and not (set(specialty) & set(d.get("specialties", []))):
            continue
        if label:
            kv_set = {f"{lab['key']}:{lab['value']}" for lab in d.get("labels", [])}
            if not (set(label) & kv_set):
                continue
        if source is not None and d.get("source") != source:
            continue
        # Cycle 4 stub has no publishedVersion; treat all entries as
        # implicitly "published=true" (existence implies a version).
        # published=false ⇒ empty result (no unpublished stubs yet).
        if published is False:
            continue
        out.append(d)
    return out


# ─── Endpoints ──────────────────────────────────────────────────────


@router.get(
    "/templates/",
    response_model=List[GuidedTemplate],
    status_code=200,
)
@router.get(
    "/templates",
    response_model=List[GuidedTemplate],
    status_code=200,
)
async def list_v2_tools_templates(
    lang: List[str] = Query(default_factory=list, description="BCP 47 language tag filter; repeatable"),
    region: List[str] = Query(default_factory=list, description="ISO 3166-1 alpha-3 region code filter; repeatable"),
    specialty: List[str] = Query(default_factory=list, description="Clinical specialty filter; repeatable"),
    label: List[str] = Query(default_factory=list, description="Filter as `key:value`; repeatable"),
    published: Optional[bool] = Query(default=None, description="true=published only, false=unpublished only, omit=both"),
    source: Optional[Literal["user", "corti"]] = Query(default=None, description="Content source filter"),
    current_user: User = Depends(get_current_user),
) -> List[GuidedTemplate]:
    """Corti §13.4 Guided Templates — ``GET /documents/templates/`` (Cycle 4 stub)."""
    # Hospital-pilot gate (REST parity with cycles 1-3)
    if not os.environ.get("ICODER_CREDENTIAL_LLM", "").strip():
        if os.environ.get("ICODER_ALLOW_DEGRADED_NO_KEY", "") != "1":
            raise HTTPException(
                status_code=503,
                detail={
                    "requestid": str(uuid.uuid4()),
                    "status": 503,
                    "type": "service_unavailable",
                    "detail": "ICODER_CREDENTIAL_LLM not set; hospital-pilot gate refuses to serve.",
                },
            )
    return [GuidedTemplate(**d) for d in _apply_filters(
        _STUB_TEMPLATES, lang=lang, region=region, specialty=specialty,
        label=label, published=published, source=source,
    )]


@router.get(
    "/sections/",
    response_model=List[GuidedSection],
    status_code=200,
)
@router.get(
    "/sections",
    response_model=List[GuidedSection],
    status_code=200,
)
async def list_v2_tools_sections(
    lang: List[str] = Query(default_factory=list, description="BCP 47 language tag filter; repeatable"),
    region: List[str] = Query(default_factory=list, description="ISO 3166-1 alpha-3 region code filter; repeatable"),
    specialty: List[str] = Query(default_factory=list, description="Clinical specialty filter; repeatable"),
    label: List[str] = Query(default_factory=list, description="Filter as `key:value`; repeatable"),
    published: Optional[bool] = Query(default=None, description="true=published only, false=unpublished only, omit=both"),
    source: Optional[Literal["user", "corti"]] = Query(default=None, description="Content source filter"),
    current_user: User = Depends(get_current_user),
) -> List[GuidedSection]:
    """Corti §13.4 Guided Sections — ``GET /documents/sections/`` (Cycle 4 stub)."""
    if not os.environ.get("ICODER_CREDENTIAL_LLM", "").strip():
        if os.environ.get("ICODER_ALLOW_DEGRADED_NO_KEY", "") != "1":
            raise HTTPException(
                status_code=503,
                detail={
                    "requestid": str(uuid.uuid4()),
                    "status": 503,
                    "type": "service_unavailable",
                    "detail": "ICODER_CREDENTIAL_LLM not set; hospital-pilot gate refuses to serve.",
                },
            )
    return [GuidedSection(**d) for d in _apply_filters(
        _STUB_SECTIONS, lang=lang, region=region, specialty=specialty,
        label=label, published=published, source=source,
    )]